### ISSUE TITLE
TypeScript 1.3

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/grunt-ts#175]
Shall we begin using TypeScript 1.3 for the development of grunt-ts?
Shall we upgrade the included compiler to 1.3?
Shall we remove 1.0?  Remove 1.1?  I don't think it would hurt to leave 1.0 and 1.1 in subfolders as artifacts.

I'm willing to do this after I finish up the `files` functionality.

I took a look.  The grunt-ts project does compile using 1.3 and from my initial review it seems that the only syntactic change to the output (other than whitespace) is where parameter defaults are provided, the parameter is compared to void 0 now.  For example:

````javascript
//old emit from 1.0 compiler:
 if (typeof addedOrChanged === "undefined") { addedOrChanged = false; }

//new emit from 1.3 compiler:
if (addedOrChanged === void 0) { addedOrChanged = false; }
````

By the way, my vote is:

 * Yes use 1.3 to develop grunt-ts
 * No, keep included compiler at 1.0 for a little while.
 * No, do not remove 1.0 or 1.1.  Add 1.3 as a subfolder and move 1.1 to a subfolder.

**Comment by nycdotnet** [comment]
Well - it's probably about time to get around to this, now that TypeScript 1.4 is out.  :-)
Assuming 1.4 compiles grunt-ts cleanly, I'll submit a PR for this ASAP.  I won't feel bad if people jump ahead of me to do it, though!!

**Comment by soernt** [comment]
I 'am facing the problem that the angularjs.TypeScript.DefinitelyType package contains features of TypeScript 1.4. They start using union types.
Is there any estimation when grant-ts supports TypeScript 1.4? By the way: I love grunt-ts.

**Comment by nycdotnet** [comment]
FYI: it supports it today via a custom compiler.  It should only take a few minutes for you to set up.  See here: https://github.com/TypeStrong/grunt-ts#compiler

The trouble is that it won't pass in the new switches.  As long as the power stays on with this big blizzard in New York, I should hopefully have grunt-ts updated to 1.4 in a week or so.

**Comment by nycdotnet** [comment]
Update - I'm working on this now.  Not quite finished yet, but it should be soon.

**Comment by soernt** [comment]
Sounds great.

**Comment by nycdotnet** [comment]
In-progress.  It's working on 1.4 and all tests are passing.

https://github.com/nycdotnet/grunt-ts/tree/update-to-1.4.1

I've got to get the new switches implemented now.

**Comment by basarat** [comment]
tip feel free to work on a feature branch locally `TypeStrong/grunt-ts` e.g. `feat/upgrade-to-1.4.1`

**Comment by nycdotnet** [comment]
ok will do for next time.

**Comment by nycdotnet** [comment]
Pull Request #206 is complete.  Please take a look.  I'll merge it into master and push to npm as version 2.1.0 in a few days if I don't hear anything.  Thanks all!

**Comment by nycdotnet** [comment]
1.4.1 merged.

**Comment by soernt** [comment]
Thank you! Works fine :-)
