### ISSUE TITLE
Docs: Alternate compiler documentation 

### ISSUE THREAD

**Issue by basarat** [TypeStrong/grunt-ts#194]
you can drive the compiler used for TypeScript from your `package.json`. Documentation was here : 

 https://github.com/TypeStrong/grunt-ts/blob/b13d823ab3fd02104df7d0d0db73a98411f6c47f/README.md#alternate-compiler-version 

 Would be nice to have this documentation back (not urgently but just tagging for memory). A client emailed ;) 

----

`grunt-ts` always ships (bundled) with the *latest* compiler. Support for legacy  projects can be enabled using the compiler override:

At runtime the plugin will look for an alternate compiler in the same `node_modules` folder. To use a different version of the TypeScript compiler install the required `typescript` version as a *peer* of `grunt-ts`. If no override was found the bundled compiler is used.  

The `package.json` would look something like this for a legacy project:

```javascript
{
  "devDependencies": {
    "grunt" : "~0.4.1",
    "grunt-ts" : "~1.9.2",
    "typescript" : "0.9.7"
  }
}
```
Note: make sure to pin the exact TypeScript version (do not use `~` or `>`).

**Comment by nycdotnet** [comment]
I believe that I fixed this in #204.  Please re-open if you disagree (or fix the language if I've made it worse).  Thanks Bas.
