### ISSUE TITLE
grunt-ts scans every file in the current directory on startup

### ISSUE THREAD

**Issue by trevj** [TypeStrong/grunt-ts#196]
We've been using grunt-ts in our project for its fast recompile feature but we've noticed that it can take several seconds for grunt-ts to report that no files need to be compiled. This significantly reduces the usefulness of the fast recompile feature.

It seems that grunt-ts performs some sort of scan of every file in the current directory on startup. I didn't dig very deeply into it but `strace grunt` indicates that every file is being `openat`-ed. We have a pretty large node_modules directory (~19k files) and so startup takes several seconds.

Do you have any idea why grunt-ts would be performing this scan? I couldn't find a similar report in the issue tracker.

**Comment by nycdotnet** [comment]
No worries - thanks for the report.
