### ISSUE TITLE
Suggestion: replace uses of os.EOL with grunt.util.linefeed

### ISSUE THREAD

**Issue by DavidRigglemanININ** [TypeStrong/grunt-ts#199]
Currently, this plugin uses os.EOL as the new line character when generating new files (such as in reference.ts). This can cause problems in cross platform development and in source control management as the generated reference files will be different depending on whether they were generated on Windows or Linux/Mac. Grunt has the ability to optionally specify the line feed character (still defaults to os.EOL) with grunt.util.linefeed (https://github.com/gruntjs/grunt-contrib-concat/issues/20). To take advantage of this, all you would need to do is update the references to os.EOL. I can do this work and create a pull request, but I want to make sure you are OK with this before spending the time (there are 14 references throughout the entire code base)

**Comment by nycdotnet** [comment]
Good point.  This would need to be referenced in the documentation as well.  If you want to submit a PR we'd be happy to accept it.

**Comment by DavidRigglemanININ** [comment]
Should I update the files in tasks-internal? Reading comments from another issue, it looks like tasks-internal is used as the internal compiler you use to turn the grunt-ts typescript into javascript

**Comment by basarat** [comment]
> Should I update the files in tasks-internal?

no need. Your understanding is correct. It will automatically get updated the next time we run `grunt update` to update the LKG. Looking forward to the PR!

**Comment by nycdotnet** [comment]
Merged.  Thanks very much @DavidRigglemanININ .  Great first PR.
