### ISSUE TITLE
preserveConstEnums

### ISSUE THREAD

**Issue by fdecampredon** [TypeStrong/grunt-ts#205]
1.4.1 add a new flag preserveConstEnums, it would be cool if it could be supported

**Comment by nycdotnet** [comment]
Agreed.  I intend to upgrade grunt-ts to support all the new 1.4 features (and include 1.4 natively) in the next week or so.  There are a lot of new switches in 1.4.  In the meantime, PRs accepted.  :-)

**Comment by nycdotnet** [comment]
Implemented in 01f239d5791227241b4d389b4cf955f81e27e744 .  PR #206 Will be pushed to npm in a few days unless I hear of any issues.
