### ISSUE TITLE
Can't get '///ts:ref=_references'.ts to work

### ISSUE THREAD

**Issue by distinctdan** [TypeStrong/grunt-ts#207]
I've got a ts project and I'm trying to get the autogenerated references transform to work, but it always says "/// No file or directory matched name "_references.ts" ///ts:ref:generated". My directory structure looks like this:

source ->
&nbsp;&nbsp;&nbsp;&nbsp;_references.ts
&nbsp;&nbsp;&nbsp;&nbsp;app ->
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;foo.ts
   
In foo.ts I've got the comment "///ts:ref=_references.ts", but it can't find my _references.ts file, which is generated by grunt-ts. Am I doing anything wrong here? Thanks.

**Comment by basarat** [comment]
@distinctdan does `src` contain something that would match `/sources/_references.ts`. Can you show us your grunt config.

**Comment by distinctdan** [comment]
Hmm, nope, src isn't matching _references. Maybe should I add it?

Heres my config:

```
development: {
    src: grunt.file.expand([
        "source/lib/**/*.ts",
        "source/global/**/*.ts",
        "source/app/classes/**/*.ts",
        "source/app/resources/**/*.ts",
        "source/app/managers/abstract-managers/**/*.ts",
        "source/app/managers/derived-managers/*.ts",
        "source/app/managers/derived-managers/dashboard/**/*.ts",
        "source/app/controllers/**/*.ts",
        "source/app/main.ts"
    ]),
    outDir: '../My.App.Folder/content/untranslated/',
    reference: 'source/_references.ts',
    options: {
        module: 'amd',
        target: 'es3',
        sourceMap: true,
        sourceRoot: '/content/untranslated',
        declaration: false
    }
},
```

**Comment by basarat** [comment]
> Maybe should I add it

Yup. `///ts:` transforms only work for files that match in `src`. Let us know if you still have issues :)

**Comment by distinctdan** [comment]
It works! Thanks for the help :) . 
By the way, it may be a good idea to add a note to the docs in case other people have the same confusion.

**Comment by nycdotnet** [comment]
@distinctdan I updated the docs for `reference`.

https://github.com/TypeStrong/grunt-ts/blob/master/README.md#reference

Thanks for the report.
