### ISSUE TITLE
HTML templates for external modules

### ISSUE THREAD

**Issue by mtraynham** [TypeStrong/grunt-ts#208]
What's the proper way to go about this?

**Comment by nycdotnet** [comment]
Sorry for not having replied sooner.  I haven't used this with external modules.  It's not how it was designed, though I suppose it wouldn't be too hard to implement as a feature.

@basarat - what do you think?

**Comment by basarat** [comment]
@mtraynham there isn't a way to do this right now. You would need the word `export` before `module` here : https://github.com/TypeStrong/grunt-ts/blob/master/tasks/modules/html2ts.ts#L29

This could perhaps be an additional customization on top of what we have currently : https://github.com/TypeStrong/grunt-ts/blob/master/docs/html2ts.md#control-generated-typescript-module-and-variable-names (customizations exist for module name and var name). PRs welcome. I don't use html2ts anymore. It was useful for bootstrapping but not needed by me anymore.

**Comment by johnman** [comment]
you can use <%=content%> and <%modulename%> with a custom template to add export and those two. That will generate a ts file you can compile that exports your html. You'll need the latest version of grunt-ts as the version before didn't create the template you specified.

**Comment by nycdotnet** [comment]
I think this is resolved now.  If not, please let me know and I will reopen.
