### ISSUE TITLE
Typescript 1.4

### ISSUE THREAD

**Issue by hdachev** [TypeStrong/grunt-ts#209]
Hey guys, any plans on upgrading the bundled compiler?
Let me know if and how I can help with catching up with tsc versions.
As far as I know the problem is with error codes having changed since 1.0.1, correct?

**Comment by basarat** [comment]
Thanks @hdachev! @nycdotnet already did all the work : https://github.com/TypeStrong/grunt-ts/pull/206 

I just pushed to npm as `v3.0.0`. Let us know if you find any issues :+1:

**Comment by hdachev** [comment]
Thanks, great work guys!
