### ISSUE TITLE
outDir not working ?

### ISSUE THREAD

**Issue by BerndWessels** [TypeStrong/grunt-ts#225]
Hi
I have the following grunt task - but when I run it it creates the compiled js and map files in the specified outDir AND ALSO in the original path next to the ts files. But I don't want them next to my ts files.

        ts: {
            default: {
                src: ["client/**/*.ts"],
                html: ["client/app/**/*.html"],
                outDir: "client/.app"
            },
            dev: {
                src: ["typings/tsd.d.ts", "client/app/**/*.ts"],
                options: {
                    //fast: 'never',
                    comments: true,
                    sourceMap: true
                }
            }
        },

Am I doing something wrong or is there a bug?

Cheers
Bernd

**Comment by nycdotnet** [comment]
What happens if you call `grunt ts:default` ?

**Comment by BerndWessels** [comment]
Yes, that only outputs it to the correct directory. I am a bit confused how it could have succeeded without the typings, but anyway it works.
Cheers
Bernd

**Comment by nycdotnet** [comment]
Good.  Run `grunt ts:default --verbose` and see if it references the definitions.  If not, do you have any triple-slash references to the definitions in your TypeScript files themselves?
