### ISSUE TITLE
html2ts does not pass tslint + possible fix

### ISSUE THREAD

**Issue by BerndWessels** [TypeStrong/grunt-ts#226]
Hi
The current output from html to ts files is not clean and does not pass tslint.

Can you please change html2ts line 29 to

    var htmlTemplate = _.template(
        '/* tslint:disable:max-line-length */\n' +
        'module <%= modulename %> {\n' +
        '\'use strict\';\n' +
        '  export var <%= varname %>: string = \'<%= content %>\';\n' +
        '}\n');

and line 47 to

    htmlContent = stripBOM(htmlContent);
    // remove newline / carriage return
    htmlContent.replace(/\n/g, "");
    // remove whitespace (space and tabs) before tags
    htmlContent.replace(/[\t ]+</g, "<");
    // remove whitespace between tags
    htmlContent.replace(/>[\t ]+</g, "><");
    // remove whitespace after tags
    htmlContent.replace(/>[\t ]+$/g, ">");
    // TODO: place a minification pipeline here if you want.

Thank you
Bernd

**Comment by nycdotnet** [comment]
Thanks for the suggestion.  I'll take a look at this next week.

**Comment by nycdotnet** [comment]
What do you think of #233 ?

I left off the "use strict" as I'm not certain I see the point.  Is that really helpful in this scenario?

I don't think we can realistically implement the edits you've asked for on the HTML content - that can be done by other libraries that are specialized for that purpose (though I think we could make it easier to plug in something to assist with that).

**Comment by nycdotnet** [comment]
Hi @BerndWessels - I've merged this PR.  Thanks for your suggestion.  I think it's a good one.
