### ISSUE TITLE
grunt-ts still using typescript v1.0.1?

### ISSUE THREAD

**Issue by davidpricedev** [TypeStrong/grunt-ts#230]
I've been using grunt-ts for a while now and I love the management of the reference file that it provides. The fact that grunt-ts pulls its own version of the tsc compiler which is quite a bit behind the latest version of typescript available via npm is starting to become an issue. I'm also using tsd to keep my d.ts files up to date, and this causes grunt-ts to fail to build anything because all the typescript definitions are utilizing features/fixes that aren't present in v1.0.1. 

why doesn't grunt-ts just use what is in the path? Then it is up to me to decide what version of the typescript compiler to use instead of the grunt-ts devs. I tried to use the compiler option, but `compiler: '%APPDATA%\\npm\\tsc'` doesn't seem to work for me. Any suggestions?

	Using the custom compiler : C:\Users\David\AppData\Roaming\npm\
	module.js:338
		throw err;
			  ^
	Error: Cannot find module 'C:\Users\David\AppData\Roaming\npm'
		at Function.Module._resolveFilename (module.js:336:15)
		at Function.Module._load (module.js:278:25)
		at Function.Module.runMain (module.js:501:10)
		at startup (node.js:129:16)
		at node.js:814:3

**Comment by nycdotnet** [comment]
We upgraded to 1.4.1 several months ago.  Are you on the latest grunt-ts?  Check your package.json file - you might be pinned to the 1.x major version.  4.0.1 is the latest.  https://www.npmjs.com/package/grunt-ts

**Comment by nycdotnet** [comment]
Also - I don't believe that Windows environment variables are supported in Grunt globs though that would probably be good to support for us since we do have a more Windows-oriented audience.
