### ISSUE TITLE
Generate definition files in a custom folder

### ISSUE THREAD

**Issue by Vadorequest** [TypeStrong/grunt-ts#231]
Following the current way to config my project:

```
grunt.config.set('ts', {
        recursive: {
            // Génère le fichier .js à côté du fichier .ts dans tous les sous-répertoires.
            src: [
                config.assetsScriptsDir + '/widget/**/*.ts'
            ],
            outDir: config.generatedScriptsDir + '/widget',
            options: {
                module: 'commonjs',
                target: 'es5',
                fast: 'never',// Ne pas recompiler sur changement, puisqu'on a un système séparé pour faire ça.
                comments: true,// On garde les commentaires pour debug, ils seront supprimés lors de la minification finale en prod.
                sourceMap: false,// Non utilisable dû au fait qu'on minifie/sandbox tout en un seul fichier.
                //sourceRoot : config.generatedScriptsDir,
                declaration: false,// Non utilisé pour le moment. Pourrait changer.
                noEmitOnError: false,// Force log errors.
                failOnTypeErrors: true,// Force log grunt errors pipeline.
                verbose: true
            }
        }
    });

    grunt.loadNpmTasks('grunt-ts');
```

If I set `declaration: true`, they are generated in my `outDir` folder, which is not good for me since this folder is a temporary folder. I would rather need to move them into a specific directory, either the source directory or another one.

What do you think?

**Comment by nycdotnet** [comment]
Hi @Vadorequest ,

I thought about this a bit, and while I think it could be useful, I think this might be a bit out of scope for grunt-ts.  This sounds like a great use for [grunt-contrib-copy](https://github.com/gruntjs/grunt-contrib-copy) or a similar plugin to run after the TypeScript compile step.

Thanks very much for writing up this issue.

**Comment by Vadorequest** [comment]
I see, I still think it should be an option inside grunt-ts module, but it
is doable through grunt-contrib-copy indeed.

Thanks.
