### ISSUE TITLE
maybe "html" is not the best name for in-lining functionality

### ISSUE THREAD

**Issue by ben8p** [TypeStrong/grunt-ts#234]
The functionality html to ts can be used with anything that needs to be in-lined as a string.
for instance, I use it to inline some copyright notice, some css, but it's limitless.

So I though maybe this could be renamed to a more generic name.

**Comment by nycdotnet** [comment]
Hi @ben8p,

Thanks for submitting this issue.  I think you're right that we could be clearer on this, but I don't want to change the API at this point.

I wonder if we could make this clearer in the documentation.  Would you be willing to submit a PR for the docs including an example of using this feature for a copyright notice or CSS?

Thanks for the suggestion.
