### ISSUE TITLE
Unable to disable grunt-ts watch feature.

### ISSUE THREAD

**Issue by RyanThomas73** [TypeStrong/grunt-ts#241]
I'm unable to find in the documentation (or through testing with variations of the fast and watch options) a way to disable grunt-ts watching the source files.

Is there an option configuration to do this or do I need to begin creating one?

**Comment by nycdotnet** [comment]
CTRL+Break should do it - or is this not what you're asking?  If you don't want the `watch` behavior, you can just not specify it in the task config in your Gruntfile.

**Comment by RyanThomas73** [comment]
Hi Steve,

My apologies for the misunderstanding. This issue can be closed. I thought grunt-ts was automatically watching the .ts files and compiling them without the watch option being set to anything but the culprit was Visual Studio. I didn't realize it's compile .ts files on save defaulted to true.

Cheers,
Ryan Thomas
