### ISSUE TITLE
vs option ignores common PropertyGroups

### ISSUE THREAD

**Issue by awn70** [TypeStrong/grunt-ts#242]
Hi,
the ```vs``` option seems to ignore common PropertyGroups in the njsproj file.
This will be ignored:
```
<PropertyGroup>
    <TypeScriptModuleKind>commonjs</TypeScriptModuleKind>
</PropertyGroup>
```
This is working:
```
<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <TypeScriptModuleKind>commonjs</TypeScriptModuleKind>
</PropertyGroup>
```
Is it a bug?
Regards
Andreas

**Comment by nycdotnet** [comment]
Hi Andreas.  I'm so glad someone is using the new `vs` feature in the wild, and with a Node.JS tools project too!  This is likely a bug in the csproj2ts library that we use.  I'll look into it.  Thanks for the report.

**Comment by nycdotnet** [comment]
Hi - would you do me a favor and edit the package.json inside grunt-ts to reference csproj2ts version 0.0.3, and then run `npm install` to update it?  I just pushed a fix to npm that should hopefully address this issue.  Let me know if not.  Thanks!

**Comment by awn70** [comment]
Hi,
it's working now, thanks!
Andreas
