### ISSUE TITLE
Rationalize Unit Tests

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/grunt-ts#247]
There are several problems with the current set of tests for grunt-ts:
  1. Many of the tests used by grunt-ts are full integration tests.  While these are effective (and they are good for testing things like editing files on disk), they are quite slow to run in aggregate.
  1. Several of the tests really are just checking that the correct parameters are passed to `tsc` - a full compile cycle should not be required to test this.
  1. Several of the tests are checking for warnings to appear, but these are not asserted.
  1. Several of the tests are expecting blocking errors to occur, but these are not asserted either.
  1. The "happy path" ends with "Done, but with errors". While this may be acceptable when running a full suite of integration tests, it would be great to be able to have a fast set of core tests that would finish with no errors present.

Any thoughts on how to move forward with this would be welcome.  I suspect that beginning a significant refactoring project for grunt-ts to not only work with grunt (meaning allow it to integrate with a test harness directly and potentially other build suites) might be part of this discussion.

**Comment by basarat** [comment]
> Several of the tests are checking for warnings to appear, but these are not asserted.

Perhaps an external test (using something like `process.exec`) that runs these grunt task and asserts that they fail (error code) would be better.

**Comment by nycdotnet** [comment]
That's a good idea.  I'm wondering if we can do any sort of hacky parallelization if we're shelling out to multiple external processes anyway.

What do you think about putting a `gruntts` property on the task or even on grunt itself for metadata?We could use it for tracking warnings raised, exceptions, etc.  Or maybe the better way forward is just to pass in a mocked Grunt object and assert the proper calls.

**Comment by basarat** [comment]
> gruntts property on the task

Perhaps call it `externaltest` similar to `test` (which will continue to function as they are now). 

> Or maybe the better way forward is just to pass in a mocked Grunt object and assert the proper calls.

^ this would be ideal. But I suspect a lot of work.

We have two proposals now. Pick either :D

**Comment by nycdotnet** [comment]
As an update, in 4.2.0, I've added/migrated about 20 tests to `commandLineAssertions.ts`, which will simply confirm that the correct switches "would be passed" to tsc if it were run, but does not actually run tsc.  While these 20 tests partially represent true growth in the number of tests, each item in commandLineAssertions only takes about 1/10th of a second, so we're about 50 seconds faster than we would be otherwise with this method when running `grunt release`.  (On my PC `grunt release` takes around 150 seconds now).

So this is good progress on items 1 and 2 above, but 3, 4, and 5 still need work.

**Comment by nycdotnet** [comment]
With v5, we've got enough examples of fast tests stuff to basically consider this resolved.  I can live with "done but with errors" for now.
