### ISSUE TITLE
Support for TypeScript 1.5/latest module kind output options 'umd' and 'system'

### ISSUE THREAD

**Issue by home-automation-community** [TypeStrong/grunt-ts#250]
grunt-ts allows to use the latest TypeScript 1.5 beta compiler with the 'compiler' option. However, compiling with option 'module': 'umd' breaks with the message: 'WARNING: Option "module" does only support "amd" | "commonjs"'

The file modules/compile.ts should be modified to allow 'umd' and 'system' module kinds.

**Comment by nycdotnet** [comment]
We're working on it. In the meantime feel free to search for that error text.  It should hopefully be fairly straightforward to delete that check.

**Comment by nycdotnet** [comment]
Should be working in 4.2.0-beta.1 which I just pushed to npm.  Please let me know if not.  Thanks for the report!
