### ISSUE TITLE
Compiling into a single file not possible with the files Array/Object

### ISSUE THREAD

**Issue by Linowitch** [TypeStrong/grunt-ts#251]
Rather this
```javascript
grunt.initConfig({
  ts: {
    compileTwoSetsOfFilesUsingArrayStyle: {
      // This will run tsc twice.  The first time, the result of the 'files1/**/*.ts' glob will be
      // passed to tsc with the --out switch as 'out/ArrayStyle/1.js'.
      // see https://github.com/gruntjs/grunt-docs/blob/master/Configuring-tasks.md#files-array-format
      files: [{ src: ['files1/**/*.ts'], dest: 'out/ArrayStyle/1.js' },
              { src: ['files2/**/*.ts'], dest: 'out/ArrayStyle/2.js' }],
      options: {
        fast: 'never'
      }
    },
```
nor this
```javascript
compileTwoSetsOfFilesUsingObjectStyle: {
      // This will run tsc twice.  The first time, the result of the 'files1/**/*.ts' glob will be
      // passed to tsc with the --out switch as 'out/ObjectStyle/1.js'.
      // see https://github.com/gruntjs/grunt-docs/blob/master/Configuring-tasks.md#files-object-format
      files: {
        'out/ObjectStyle/1.js': ['files1/**/*.ts'],
        'out/ObjectStyle/2.js': ['files2/**/*.ts']
      },
      options: {
        fast: 'never'
      }
```
is setting the -out switch for the compiler as in the description explained.
Only if I'm using the options out it is working, but then I would have to setup one subtask per file...

Bests,
Sascha

**Comment by nycdotnet** [comment]
You're absolutely correct.  This is broken and our tests didn't pick it up.  Very sorry - will resolve ASAP.

**Comment by nycdotnet** [comment]
I just pushed version 4.1.1 - will you check it out and let me know if you agree that this is resolved.  Thanks for the report and sorry for the regression.

**Comment by seanmailander** [comment]
The changes in 97ad3999847b0cc7e8d78ac8e1ef99f24284fde5 broke the tsc command when paths include spaces.
For our configuration: 
 - Previously utilised target.out, which is a relative path
 - Now uses outFile, which is absolute

Assume something like this is needed:
> outFile = '"' + path.resolve(outFile) + '"';

**Comment by nycdotnet** [comment]
@seanmailander - thanks for the report.  I just pushed 4.1.2 to npm - would you please take a look?

**Comment by seanmailander** [comment]
@nycdotnet looks-great-runs-great, thanks!

**Comment by nycdotnet** [comment]
Glad to hear it.

@Linowitch - thank you for the original report.  I think things are fixed so I am going to close this issue.  Please let me know if it is not fixed for you.  Thanks!!
