### ISSUE TITLE
Cannot compile with decorators (tsc master)

### ISSUE THREAD

**Issue by mtraynham** [TypeStrong/grunt-ts#253]
This happens if you point the compiler at `master` checkout.

Usage of decorators now throws a warning:
https://github.com/Microsoft/TypeScript/pull/3330

Can I just suggest that instead of/along with adding another flag, we also allow add a configuration object for CLI arguments.  That would allow us to circumvent future incompatibilities.

Note, you cannot add arguments to the compiler option.  `compiler: "./node_modules/typescript/bin/tsc --experimentalDecorators"`

**Comment by nycdotnet** [comment]
This is working in this branch.  https://github.com/TypeStrong/grunt-ts/tree/update-to-typescript-1.5.0-beta 

I have been super busy at home so I haven't yet finished implementing everything yet.  Please reply in #246 .
