### ISSUE TITLE
Single output file not working.

### ISSUE THREAD

**Issue by dbeckwith** [TypeStrong/grunt-ts#257]
I'm having an issue with the --out parameter option that's supposed to output everything into one file.
In my `Gruntfile.js`, in `grunt.initConfig` I have this configuration:
```
    ts: {
      options: {
        module: 'commonjs',
        fast: 'never',
        target: 'es5',
        declaration: false,
        sourcemap: false,
        removeComments: true,
        noImplicitAny: false
      },
      main: {
        src: ['src/**/*.ts', 'lib/**/*.ts'],
        out: 'build/main.js'
      }
    }
```
So it should output to `build/main.js` right? But instead all I get is a blank file called `main.js` and each individual file gets compiled in its source folder. For example, I have these files:
```
build/
lib/
  bla.ts
src/
  test.ts
```
and I end up with this after compiling (and some cleaning):
```
build/
  main.js (empty)
lib/
  bla.ts
  bla.js
src/
  test.ts
  test.js
```

Something I'm doing wrong?

**Comment by nycdotnet** [comment]
What version of grunt-ts do you have?

**Comment by dbeckwith** [comment]
4.1.2

**Comment by nycdotnet** [comment]
I just created a brand new folder, did `npm install grunt-ts`, and set up `src/test.ts` and `lib/bla.ts`.  When I compile using the below Gruntfile.js by running `grunt` (to get the default), grunt-ts seemingly works correctly by compiling the code in `bla.ts` and `test.ts` to `build/main.js`.

This is the entirety of the Gruntfile.js I just used to test:

```js
module.exports = function(grunt) {
  grunt.initConfig({
    ts: {
      options: {
        module: 'commonjs',
        fast: 'never',
        target: 'es5',
        declaration: false,
        sourcemap: false,
        removeComments: true,
        noImplicitAny: false
      },
      main: {
        src: ['src/**/*.ts', 'lib/**/*.ts'],
        out: 'build/main.js'
      }
    }

  });
  grunt.loadNpmTasks("grunt-ts");
  grunt.registerTask("default", ["ts"]);
};
```

Would you please run `grunt --verbose` for me and post the output?

**Comment by dbeckwith** [comment]
I've modified my folder layout slightly since then, but I'm still getting essentially the same thing. Now all of my source files are in one folder, but I still get a blank output file, and individual compiled files in the source directory.

```
Running "ts:src" (ts) task
Verifying property ts.src exists in config...OK
Files: src/_ref.d.ts, src/cli.ts, src/lambdacalc.ts
Options: allowBool=false, allowImportModule=false, compile, declaration=false, mapRoot="", module="commonjs", noImplicitAny=false, noResolve=false, comments=null, removeComments, sourceMap, sourceRoot="", target="es5", verbose=false, fast="never", compiler="", htmlModuleTemplate="<%= filename %>", htmlVarTemplate="<%= ext %>", htmlOutDir=null, htmlOutDirFlatten=false, failOnTypeErrors, noEmitOnError=false, preserveConstEnums=false, suppressImplicitAnyIndexErrors=false, sourcemap
Compiling...
Using tsc v1.4.1
"/home/sonaxaton/WebstormProjects/lambdacalc/src/_ref.d.ts" "/home/sonaxaton/WebstormProjects/lambdacalc/src/cli.ts" "/home/sonaxaton/WebstormProjects/lambdacalc/src/lambdacalc.ts" --sourcemap --removeComments --target ES5 --module commonjs --out "/home/sonaxaton/WebstormProjects/lambdacalc/bin/lib.js"



TypeScript compilation complete: 2.58s for 3 typescript files
```

**Comment by nycdotnet** [comment]
Ah ok I know what this is.  TypeScript doesn't allow external modules to be concatenated with `--out`, but they don't provide a warning either.  Take a look here: https://github.com/Microsoft/TypeScript/issues/1544

We should probably provide a warning if a module system is used with `out` since `tsc` doesn't.

**Comment by nycdotnet** [comment]
This will be in the next major version of grunt-ts:

![usingoutwithexternalmodules](https://cloud.githubusercontent.com/assets/3755379/8022366/9664d628-0c9a-11e5-90e6-50da95b955d3.PNG)

**Comment by dbeckwith** [comment]
Ah okay, thanks!

**Comment by nycdotnet** [comment]
Check out Browserify or WebPack to do the concatenation.  Thank you for the report.

**Comment by DerToti** [comment]
Shouldn't be this working now with module ``amd`` and ``--outFile``?
Is this supported by `grunt-ts`? I wanted to have grunt-ts (tsc) to concatenate the files.

**Comment by nycdotnet** [comment]
They are adding concatenation of AMD and SystemJS modules to TypeScript 1.8 I think.  Tsc 1.7 and lower can't do it yet.  We plan to remove the warning in a future version.

**Comment by nycdotnet** [comment]
See here: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#option-to-concatenate-amd-and-system-modules-into-a-single-output-file

**Comment by DerToti** [comment]
ah ok thx for the information :)
