### ISSUE TITLE
Force compilation even if no changes have occurred

### ISSUE THREAD

**Issue by azanebrain** [TypeStrong/grunt-ts#263]
When compiling a fresh build (after a `clean` for example), grunt-ts won't compile typescript files because no changes have occurred, and throws the following message:

```
No file changes were detected. Skipping Compile


TypeScript compilation complete: 0.00s for 0 typescript files

Done, without errors.
```

IMO there should be a flag to set whether grunt-ts should run even if there are no changes so a fresh build can be created.

**Comment by nycdotnet** [comment]
Try fast: 'never'.

**Comment by basarat** [comment]
> Try fast: 'never'.

That would work. Also you can clear the cache `.tscache` folder.

**Comment by nycdotnet** [comment]
Hi @azanebrain - I hope either of these two suggestions resolved your issue.  Please let us know if not.
