### ISSUE TITLE
Support for --experimentalDecorators option

### ISSUE THREAD

**Issue by Verdier** [TypeStrong/grunt-ts#266]
Since the release of typescript 1.5, we need to add the `--experimentalDecorators` option to support decorators. Do you plan to add it ?

Thanks for this incredible project.

**Comment by nycdotnet** [comment]
Hi,
I will be working on this today.  For now, you can get this working if you install our beta which lets you pass arbitrary switches.  Docs here:

https://github.com/TypeStrong/grunt-ts/tree/update-to-typescript-1.5.0-beta

**Comment by nycdotnet** [comment]
This should be resolved with v4.2.0 published just now.   Please let me know if not.

Thanks for the kind feedback.  We're glad you like it!  :-)

**Comment by Verdier** [comment]
Thanks !

2015-07-22 4:56 GMT+02:00 Steve Ognibene <notifications@github.com>:
