### ISSUE TITLE
Add project option for tsc --project command line argument

### ISSUE THREAD

**Issue by JeroMiya** [TypeStrong/grunt-ts#269]
Typescript 1.5 has a --project command line argument to specify a folder with a tsconfig.json file with compiler options. Support this option as an alternative to specifying compiler options in the grunt task, so that editor settings and grunt build settings can stay in sync.

Alternatively, some functionality to generate a tsconfig.json file that matches the grunt task?

**Comment by nycdotnet** [comment]
I agree.  Discussion is here: https://github.com/TypeStrong/grunt-ts/issues/202.

I intend to implement this soon. Thanks for your patience!
