### ISSUE TITLE
Create Jasmine testing template that works with flat module style

### ISSUE THREAD

**Issue by jeffmay** [TypeStrong/grunt-ts#27]
When running unit tests with Jasmine out of the box, I see a bunch of failures about angular not being defined and other things. I think it is important for the angular community to know that there is a simple and fast way to get started with unit tests.

I think the easiest option might be to create a grunt-contrib-jasmine template that loads the amd loader file before loading all the test scripts.

**Comment by nycdotnet** [comment]
@jeffmay Did you ever figure this out?

**Comment by jeffmay** [comment]
Nope. I don't think this is the right direction to go anymore. The grunt-ts folks have worked out a solution to make compilation faster using decoupled modules. This is a better approach.
