### ISSUE TITLE
html2ts should honor outDir setting

### ISSUE THREAD

**Issue by hoeni** [TypeStrong/grunt-ts#271]
When generating a .ts file from .html it should be stored in the configured outDir (if there is one configured).
At the moment, the .ts file is generated in the source directory, only the derived .js and .map files are stored in the outDir correctly.

If using outDir for that is not an option, maybe one could introduce a separate option for that (e.g. 'htmlOutDir')?

**Comment by sethx** [comment]
Valid point. I personally don't use outDir so it hadn't occured to me that this may be necessary, but I'll make changes to honor outDir.

**Comment by sethx** [comment]
Btw, i just checked the source, and "htmlOutDir" is already a valid option.

**Comment by hoeni** [comment]
At least "htmlOutDir" has no effect in my case...

**Comment by sethx** [comment]
I'll test it later this week. Thx for reporting!

**Comment by nycdotnet** [comment]
This will be fixed in #275 when that is complete (still work-in-progress).

**Comment by nycdotnet** [comment]
Hello, @hoeni - Would you please try grunt-ts@5.0.0-beta.2 and let me know if it resolves your issue?  Please note that this is a significant rewrite of the options resolution logic so it may have other issues.  Let me know if you see anything.

**Comment by nycdotnet** [comment]
This should be corrected in v5, just released to npm.  Please reopen if not.

**Comment by hoeni** [comment]
Sorry, I didn't find the time yet to test it yet. I'll reopen if there are any issues!

**Comment by nycdotnet** [comment]
No worries!  Thanks for the report.
