### ISSUE TITLE
Reference comments littering the Javascript file

### ISSUE THREAD

**Issue by AnthoniG** [TypeStrong/grunt-ts#272]
Gruntfile.js
```
module.exports = function (grunt) {

    // load the task
    grunt.loadNpmTasks("grunt-ts");

    // Configure grunt here
    grunt.initConfig({
        ts: {
            dev: {                          // a particular target
                src: ["app/**/*.ts"], // The source typescript files, http://gruntjs.com/configuring-tasks#files
                html: ["app/**/*.html"], // The source html files, https://github.com/basarat/grunt-ts#html-2-typescript-support
                reference: "./app/ref.ts",  // If specified, generate this file that you can use for your reference management
                out: 'scripts/out.js',         // If specified, generate an out.js file which is the merged js file
                watch: 'app',
                options: {
                    compile: true,                 // perform compilation. [true (default) | false]
                    sourceMap: true,               // generate a source map for every output js file. [true (default) | false]
                    noImplicitAny: true,          // set to true to pass --noImplicitAny to the compiler. [true | false (default)]
                    target: 'es5',
                    comments: false
                }
            }
        }
    });

    grunt.registerTask("default", ["ts:dev"]);
```

When I look inside the out.js file it has loads of /// <reference comments inside and I can not seem to get rid of them. It also has the full list right at the end of the file.

Is this normal ? If not, how do I get rid of them ?

--

Also, I think this is a tsc thing, when using module Controllers{} and I have multiple controllers in multiple .ts file, the output javascript has multiple var Controllers. Is this a tsc thing or can I change it in grunt-ts ?

**Comment by nycdotnet** [comment]
Hi,
Reference comments are preserved by tsc even if `--removeComments` are preserved.  I don't know the reasoning for this, but I believe that it is intentional.  A minifier like uglify should be able to remove these with no issues.

If you're using a tool like grunt-ts and an editor that supports the TypeScript language service like Visual Studio or Atom you shouldn't technically need reference comments at all.

I don't know what you mean by "has the full list right at the end of the file".

Regarding the multiple `var Controllers` thing - this is just how TypeScript emits it. While it seems redundant (and it is somewhat), the different IIFEs are actually useful since they allow each module (aka namespace) to have its own "extra private" scope that isn't shared with other places where the namespace is used.

I'm not sure grunt-ts can help you with this.  I know I still have a to-do to document Uglify integration.

**Comment by AnthoniG** [comment]
@nycdotnet Thanks Steve.

By "has full list at the end of the file" I mean this is what is outputted in my javascript file, right at the bottom.
```
/// <reference path="../vendor/typings/tsd.d.ts" />
/// <reference path="services/services.ts" />
/// <reference path="directives/directives.ts" />
/// <reference path="templates/dashboard/tplDashboard.html.ts" />
/// <reference path="templates/dashboard/tplProjectList.html.ts" />
/// <reference path="templates/login/tplLoginForm.html.ts" />
/// <reference path="templates/login/tplLogoutForm.html.ts" />
/// <reference path="templates/projects/dialogs/tplModalNewEssRun.html.ts" />
/// <reference path="templates/projects/dialogs/tplModalNewWebProject.html.ts" />
/// <reference path="templates/projects/web/tplWebProjectDashboard.html.ts" />
/// <reference path="templates/projects/web/tplWebProjectNew.html.ts" />
/// <reference path="configs/config.ts" />
/// <reference path="configs/run.ts" />
/// <reference path="controllers/dashboard/DashboardController.ts" />
/// <reference path="controllers/dashboard/ProjectListCtrl.ts" />
/// <reference path="controllers/login/LoginController.ts" />
/// <reference path="controllers/login/LogoutController.ts" />
/// <reference path="controllers/projects/dialogs/EssProjectWizardCtrl.ts" />
/// <reference path="controllers/projects/dialogs/WebProjectWizardCtrl.ts" />
/// <reference path="controllers/projects/web/WebProjectDashboardCtrl.ts" />
/// <reference path="controllers/projects/web/WebProjectNewCtrl.ts" />
/// <reference path="controllers/shell/ShellController.ts" />
/// <reference path="interfaces/SystemInterfaces.ts" />
/// <reference path="services/blocks/GlobalScopeSvc.ts" />
/// <reference path="services/dashboard/ProjectListSvc.ts" />
/// <reference path="services/projects/web/WebProjectSvc.ts" />
/// <reference path="services/projects/web/WebRunnerArticlesSvc.ts" />
/// <reference path="services/projects/web/WebRunnerEssSvc.ts" />
/// <reference path="services/projects/web/WebRunnerImageSvc.ts" />
/// <reference path="services/projects/web/WebRunnerScopiousSvc.ts" />
/// <reference path="services/projects/web/WebRunnerYoutubeSvc.ts" />
/// <reference path="services/users/UserModelService.ts" />
/// <reference path="services/users/UserService.ts" />
/// <reference path="controllers/controllers.ts" />
/// <reference path="main.ts" />
/// <reference path="constants/AppConstants.ts" /> 
//# sourceMappingURL=out.js.map
```

As you say, an uglifier *should* get rid of this though. (no worries on documentation of this, you mentioned you were doing it. I am not at the stage I need it yet anyway).

My editor is InjelliJ IDEA and I think (though not 100% certain) that it needs the references at the top for it's intellisense.

**Comment by basarat** [comment]
> /// <reference comments inside and I can not seem to get rid of them

If you use `reference: "./app/ref.ts"` we generate a reference file with these comments. And then TypeScript will output the .js with these reference comments. 

Not really an issue with `grunt-ts`. It's doing what you asked it to do :rose:
