### ISSUE TITLE
Templates in grunt targets resolved inconsistently

### ISSUE THREAD

**Issue by bjorm** [TypeStrong/grunt-ts#273]
I run grunt-ts 4.2.0 and I have defined two targets:
```javascript
    ts: {
      dev: {
        options: {
          sourceMap: true
        },
        src: '<%= typescript.src %>',
        outDir: '<%= typescript.outDir %>',
        baseDir: '<%= typescript.baseDir %>'
      },
      prod: {
        options: {
          sourceMap: false
        },
        src: '<%= typescript.src %>',
        outDir: '<%= typescript.outDir %>',
        baseDir: '<%= typescript.baseDir %>'
      }
    }
```
If I run either target, I get
> Warning: Unable to create directory "path\to\output\<%= typescript.baseDir %>" (Error code: ENOENT). Use --force to continue.

When I output ```target``` at https://github.com/TypeStrong/grunt-ts/blob/master/tasks/modules/compile.ts#L140 (where I think the error occurs), I get:
```javascript
{ options: { sourceMap: true, mapRoot: undefined, sourceRoot: undefined },
  src: '<%= typescript.src %>',
  outDir: 'target/tmp/foo/src',
  baseDir: '<%= typescript.baseDir %>',
  out: undefined,
  reference: undefined }
```

Why is outDir correctly resolved but not src or baseDir?

**Comment by nycdotnet** [comment]
Hi,
There is a bit of a problem with the order in which we resolve things that may be causing this.  I'm working on parameter resolution and templates now as part of the tsconfig.json support and I'll be sure to use your gruntfile in a test case.  Sorry about that.  It should be fixed soon.  Can you get away with hard-coding the values in your gruntfile for now (or just use variables instead of templates so they get evaluated ahead of time)?

**Comment by nycdotnet** [comment]
This will be fixed in #275 when that is complete (still work-in-progress).

**Comment by bjorm** [comment]
Thanks for the quick response. No, it is not a big deal. Just thought I'd mention it. Should I close this issue since it is tracked elsewhere now?

**Comment by nycdotnet** [comment]
Nah I'll close it when #275 lands.

**Comment by nycdotnet** [comment]
Hello, @bjorm - Would you please try grunt-ts@5.0.0-beta.2 and let me know if it resolves your issue?  Please note that this is a significant rewrite of the options resolution logic so it may have other issues.  Let me know if you see anything.

**Comment by nycdotnet** [comment]
This should be corrected in v5, just released to npm.  Please reopen if not.
