### ISSUE TITLE
Any way to get this working with typescript@next?

### ISSUE THREAD

**Issue by timpcc** [TypeStrong/grunt-ts#279]
Is there any way to get this to target typescript@next rather than the version bundled with the task itself?
This may be simple, but I'm pretty new to grunt and node, so you please excuse my ignorance.

Thanks for any help,
Tim

**Comment by basarat** [comment]
> Is there any way to get this to target typescript@next rather than the version bundled with the task itself?

Lots of ways. Checkout https://github.com/TypeStrong/grunt-ts#compiler feel free to ask further if documentation is unclear :rose:
