### ISSUE TITLE
Typescript 1.6.2 released

### ISSUE THREAD

**Issue by awjreynolds** [TypeStrong/grunt-ts#280]
Title says it all really.

**Comment by Zjaaspoer** [comment]
+1

**Comment by DrColossos** [comment]
+1

**Comment by nycdotnet** [comment]
Update your package.json, run npm install, and you will have 1.6.

If you need switches that aren't supported by grunt-ts yet, look into the additional parameters option.

We'll update to 1.6 automatically once time allows.  Thanks.

**Comment by ravishivt** [comment]
This might be naive, but why not make the grunt-ts package use whatever version of tsc that the user has installed.  You could also provide a config option to allow the user to specify a custom tsc path if they don't want to use the one in $PATH.

**Comment by nycdotnet** [comment]
We use a "contained" typescript plugin as versioned by package.json since this is fairly standard for Grunt plugins.  It lets different projects on a computer use different versions of TypeScript, and makes cross-platform compatibility very slightly easier, among other benefits.

We do supply a config option to allow the user to specify a custom tsc path: https://github.com/TypeStrong/grunt-ts#compiler

**Comment by logankd** [comment]
+1

**Comment by Gouigouix** [comment]
Hi @nycdotnet 
Please release 5.0.0 ;o)

Thx for good jobs

**Comment by nycdotnet** [comment]
I am going to try to release it today.  I'll follow up quickly with 5.0.1 which will have TypeScript 1.6.  Thanks everyone for the feedback.

**Comment by Gouigouix** [comment]
Thx a lot @nycdotnet

**Comment by nycdotnet** [comment]
Hi all - I've just published grunt-ts `5.1.0-beta.1` which includes support for TypeScript 1.6.

Here's the PR which is still in-progress: https://github.com/TypeStrong/grunt-ts/pull/283

I'm keeping track of a few issues there.  If you run into any issues, please let me know!  Thanks.

**Comment by nycdotnet** [comment]
I've just published grunt-ts 5.1.0 to npm which has full support for TypeScript 1.6.  Please open a new issue if you run into any difficulty.  Thanks!
