### ISSUE TITLE
How to add flag jsx?

### ISSUE THREAD

**Issue by cyrilgandon** [TypeStrong/grunt-ts#282]
I see that a commit have been made to allow tsx files : https://github.com/TypeStrong/grunt-ts/commit/14b92069f749aa74c8bd59a032955f9d4be21c8a

That's nice, but when I try to add my tsx files:

    files: {
        'dist/js': ['**/*.ts', '**/*.tsx']
    },

I got the error:

> error TS17004: Cannot use JSX unless the '--jsx' flag is provided.

How am I supposed to specify the jsx flag with grunt-ts?

Note that tsx support is for ts 1.6, that's why I also specify a custom compiler

    options: {
        compiler: './node_modules/typescript/bin/tsc'
    },

**Comment by basarat** [comment]
Use additional flags : https://github.com/TypeStrong/grunt-ts#additionalflags

Closing the issue for now. Feel free to query if it is still unclear :rose:

**Comment by cyrilgandon** [comment]
That was deepely burried in the docs, thank you :+1:

**Comment by basarat** [comment]
Its at the top : https://github.com/TypeStrong/grunt-ts#support-for-tsc-switches

![image](https://cloud.githubusercontent.com/assets/874898/10303131/4dd7f9ee-6c5d-11e5-9158-f9cc2fccb041.png)


 But its always a matter of if *if you know ... you can find it*. I think I probably asked the same question the first time I needed it :)

I envy the dedication Steve shows to docs.

**Comment by cyrilgandon** [comment]
No excuses, i'm just blind I guess. I've passed like 30 minutes to read all flags one by one, and I have not seen that big additionalFlags feature. :sleepy: 
Nice doc :+1: 
Terrible users :)
