### ISSUE TITLE
Fix tsconfig.json exclude support to support files

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/grunt-ts#285]
Officially, the tsconfig.json exclude property can support file names.  Current implementation in grunt-ts only supports directories.  (https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#exclude-property-support-in-tsconfigjson)

**Comment by errorx666** [comment]
:+1: This is preventing me from excluding the `typings/main.d.ts` file generated by [typings](/typings/typings), which results in a long list of duplicate definition errors.
