### ISSUE TITLE
Use jsx from tsconfig

### ISSUE THREAD

**Issue by vp2177** [TypeStrong/grunt-ts#294]
If `tsconfig.json` contains the `jsx` option, it should be passed to `tsc`, as with other compilerOptions.

    "compilerOptions": {
      "module": "amd",
      "jsx": "foo"
    }

Currently when using `tsconfig: true`, `.tsx` files are compiled as well, by default, however if they actually contain TSX the compilation fails as the `--jsx` option is not passed to `tsc`, and it can only be achieved by using `additionalFlags: '--jsx foo'`

**Comment by nycdotnet** [comment]
This is supported in `5.1.0-beta.1` which you can get from npm.  Please let me know if it fixes your issue.

**Comment by nycdotnet** [comment]
This is supported in 5.1.0 which I've just pushed to npm.  If there is an issue, please re-open this ticket. Thanks!

**Comment by vp2177** [comment]
Thank you, confirmed fixed.
