### ISSUE TITLE
Keep directory structure for output

### ISSUE THREAD

**Issue by bennyn** [TypeStrong/grunt-ts#301]
Hello,

I saved my TypeScript code in the follwoing directory:
- `/ts/Validation/ZipCodeValidator.ts`

And in my `ts.js` I configured:

```javascript
module.exports = {
  build: {
    src: ['ts/**/*.ts'],
    outDir: 'build'
  }
};
```

When I now run the task `grunt ts:build`, then the JavaScript (compiled from the TypeScript) ends up being in `build`, which is exactly what I want. But unfortunately it does not keep the directory structure.

So I am missing the "Validation" directory inside my "build" directory. It looks like the "outDir" option does a flat mapping without keeping the original source structure. Am I correct? If yes, is there an option to keep the original directory structure?

Thanks for your help and big Kudos to your project!

Benny

**Comment by bennyn** [comment]
I got it fixed! I had to change:

```javascript
module.exports = {
  build: {
    src: ['ts/**/*.ts'],
    outDir: 'build'
  }
};
```

into:

```javascript
module.exports = {
  build: {
    src: ['ts/**/*'],
    outDir: 'build'
  }
};
```

But that's very strange because other modules like [gruntjs/grunt-contrib-coffee](https://github.com/gruntjs/grunt-contrib-coffee) keep the directory structure when using the `/**/*.extension` pattern.

**Comment by nycdotnet** [comment]
That's unusual.  I want to look into this.  Thanks for the report.

**Comment by nycdotnet** [comment]
What's happening is that TypeScript is inferring a baseDir from the TypeScript files that are present.  Your best bet is to specify a rootDir option.  If your gruntfile looked like this, I believe everything would work as expected.

```javascript
module.exports = function(grunt) {
  grunt.initConfig({
    ts: {
      build: {
        src: ['ts/**/*.ts'],
        outDir: 'build',
        options: {
          rootDir: '.'
        }
      }
    }
  });
  grunt.loadNpmTasks("grunt-ts");
  grunt.registerTask("default", ["ts"]);
};
```

We need to improve how this works now that TypeScript has built-in baseDir support via a switch and tsconfig.json.  See https://github.com/TypeStrong/grunt-ts/issues/300 .  I'll close this again.  If you have any questions or thoughts, I'd love to hear them in the other thread.  Thanks again for the report!
