### ISSUE TITLE
tsconfig.json completely ignored

### ISSUE THREAD

**Issue by ealves-pt** [TypeStrong/grunt-ts#306]
Hey guys.

When I run grunt-ts it ignores my ```tsconfig.json``` file and nothing is generated.

My tsconfig.json looks like this:

```
{
    "compilerOptions": {
        "module": "amd",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "isolatedModules": false,
        "jsx": "react",
        "noLib": false,
        "preserveConstEnums": true,
        "outDir": "../build",
        "sourceMap": false,
        "newLine": "LF"
    },
    "filesGlob": [
        "./**/*.ts",
        "./**/*.tsx"
    ],
    "exclude": [
        ".baseDir.ts"
    ],
    "files": [
        "./_all.d.ts",
        "./App.ts",
        "./AppModule.ts",
        "./AppModuleConfig.ts"
    ]
}
```

And my grunt task is like this:

```
ts: {
      default: {
        tsconfig: './app/tsconfig.json'
      }
},
```

Am I missing something?

**Comment by Niondir** [comment]
This works for me:

		ts: {
			options: {
				fast: 'never'
			},
			build: {
				tsconfig: {
					tsconfig: "./src/",
					passThrough: true
				}
			}
		},

**Comment by ealves-pt** [comment]
No lucky with that configuration.

**Comment by nycdotnet** [comment]
Hi - sorry for the delay.  I've been very busy with a new job and baby and a few other projects.  I will try to look into this as soon as possible.

**Comment by nycdotnet** [comment]
@ealves-pt What version of TypeScript and grunt-ts do you have?  Please run this in your command line from the same folder as your `gruntfile.js`, and see if it runs TypeScript as you expect:

```txt
node node_modules\typescript\lib\tsc.js --project app
```

(if you need to fix this at all to get it working, let me know how)

By the way - please re-read the docs in the grunt-ts readme about how to use the tsconfig option.  The `exclude` property is ignored if a `filesGlob` is specified.

**Comment by ealves-pt** [comment]
@nycdotnet the current versions in user are: typescript@1.6.2 and grunt-ts@4.2.0.

Running that command works as expected.

Regarding the ```exclude``` config I already dropped it my config file.

**Comment by nycdotnet** [comment]
Ah ok.  grunt-ts added support for tsconfig.json in v5.  Update to the latest grunt-ts (5.1.1 as of today) and it should hopefully work OK.

**Comment by ealves-pt** [comment]
Worked like a charm. Thank you very much for the help. :+1:
