### ISSUE TITLE
Mistake in source code don't break grunt tasks

### ISSUE THREAD

**Issue by mironx** [TypeStrong/grunt-ts#308]
I have problem that event I have mistake in source code (type script) it finished without error. 
I am using: 
"grunt": "latest",
"grunt-ts": "v5.1.0",
"grunt-cli": "latest"

It is problem e.g. form continuous development.  

![grunt_webstorm](https://cloud.githubusercontent.com/assets/476990/11142914/1cf1328a-89f1-11e5-9ca9-71bb860b3418.png)

**Comment by mironx** [comment]
I had to back to grunt-ts v4.2.0. And compilation build was stopped when ts return error.
1. What should be put to configuration in the latest version 5.1.0 to has the same behavior.  
2. Is there description of this change as breaking change or it is bug?
![image](https://cloud.githubusercontent.com/assets/476990/11145886/c1cc63e8-8a09-11e5-9c2d-571b3f028298.png)

**Comment by Niondir** [comment]
But then you do not have proper tsconfig support. We have the same issue using this config:

    	ts: {
			options: {
				fast: 'never'
			},
			build: {
				tsconfig: {
					tsconfig: "./src/",
					passThrough: true
				}
			}
		}

**Comment by Niondir** [comment]
**Found this:**
    var isSuccessfulBuild = (!isError || (isError && isOnlyTypeErrors && !options.failOnTypeErrors));

**Done that:**

		ts: {
			options: {
				fast: 'never',
				failOnTypeErrors: true
			},
			build: {
				tsconfig: {
					tsconfig: "./src/",
					passThrough: true
				}
			}
		},

**Works for me**

**Comment by Niondir** [comment]
Documentation says:

    true (default), false - fail Grunt pipeline if there is a type error. (See also noEmitOnError)

**Comment by nycdotnet** [comment]
Hi - sorry for the delay.  I've been very busy with a new job and baby and a few other projects.  I will try to look into this as soon as possible.

**Comment by nycdotnet** [comment]
Are you setting `failOnTypeErrors` to false?  The default is true which means if there is a type error, the build should fail.  I just did a simple test with v5.1.0 and grunt did fail for me.  If you're not setting `failOnTypeErrors` to false, would you mind sharing the `ts` part of your gruntfile?

**Comment by Niondir** [comment]
@nycdotnet see my last post. I definitely have to set failOnTypeErrors = true explicitly. Since the default seems to be false in fact.

**Comment by johnman** [comment]
I just tried with setting failOnTypeErrors and it didn't fail even though I had type errors. I'm guessing it's defaulting to false.

**Comment by nycdotnet** [comment]
Can you confirm the version of TypeScript that you have?

**Comment by johnman** [comment]
1.6.2 thanks

**Comment by mironx** [comment]
I am sorry for delay too.
1. ts version: 1.6.2
2. I have test both: noEmitOnError: true and noEmitOnError: false
for true it just not generate output but still grunt process finish with success

**Comment by nycdotnet** [comment]
I looked at this last night and I think I found the issue.  A patch should be out soon.

**Comment by mironx** [comment]
Ok. I will test when will be ready.

**Comment by johnman** [comment]
I'll see if I can test this over the weekend. Question: from my quick scan it seems that the default is not to fail in grunt if there is a build problem. Is this because of support of ts config and ide support? Thanks

**Comment by nycdotnet** [comment]
The thing you saw was probably where I converted failOnTypeErrors to null. That is in a "TypeScript" defaults section and I'm just being academic since TypeScript has no such switch.  failOnTypeErrors gets defaulted to true if it's not set with this patch (which wasn't happening before).  It had been set properly on the default config object, but it just wasn't getting copied over.

**Comment by mironx** [comment]
I have tested. It works :-). Thank you very match. 
Have nice weekend.

**Comment by nycdotnet** [comment]
Great.  Thanks for the report!
