### ISSUE TITLE
Support for 1.7

### ISSUE THREAD

**Issue by joskuijpers** [TypeStrong/grunt-ts#311]
Hi folks,

How is support for 1.7 coming along? I would love to use its bugfixes and its new module+es6 features.

**Comment by nycdotnet** [comment]
You can use it right away by updating your package.json, running npm install, and then using the additionalFlags feature to pass any switches that are not supported yet.

https://github.com/TypeStrong/grunt-ts/blob/master/README.md#additionalflags

Native support will be a week or two out, but PRs accepted.

**Comment by joskuijpers** [comment]
Oh haha, I see that I already use 1.7.3 after updating my typescript package.

Thanks!

**Comment by nycdotnet** [comment]
Native support for 1.7.3 was implemented in `5.3.0-beta.2`.  Please check it out if you have a chance.  The final release should be in a week or two depending on if I hear anything bad.

**Comment by nycdotnet** [comment]
See #320.

**Comment by nycdotnet** [comment]
This is resolved via a warning in grunt-ts v5.3.0 which was just pushed to npm. Please comment or re-open if there are any remaining issues. Thank you for contributing!
