### ISSUE TITLE
Warning: pattern.indexOf is not a function Use --force to continue.

### ISSUE THREAD

**Issue by jounii** [TypeStrong/grunt-ts#319]
Trying to run the ts command causes error:

```
Warning: pattern.indexOf is not a function Use --force to continue.
```

I tried to debug, but could not find the cause. 

grunt-cli v0.1.13
grunt v0.4.5
typescript v1.7.3

Tried all grunt-ts versions until 4.2.0 which worked without issues.

Gruntfile.js configuration:
```
   ts: {
            development: {
                src: ['src/ts/**/*.ts'],
                outDir: 'src/js',
                options: {
                    module: 'amd',
                    target: 'es5',
                    sourceMap: true,
                    declaration: false,
                    noImplicitAny: false,
                    comments: true
                }
            }
    }
```

Maybe there's something I'm missing blindly, but could not find it nor all the results Googling the same error just related mostly to grunt "files" needing to be array of objects instead of object.

**Comment by basarat** [comment]
Is there any stack trace? :rose:

**Comment by jounii** [comment]
Google told there was hidden (?) --stack parameter.

```
TypeError: pattern.indexOf is not a function
    at /Users/xxx/node_modules/grunt/lib/grunt/file.js:55:29
    at Array.forEach (native)
    at processPatterns (/Users/xxx/node_modules/grunt/lib/grunt/file.js:53:34)
    at Object.file.expand (/Users/xxx/node_modules/grunt/lib/grunt/file.js:110:17)
    at /Users/xxx/node_modules/grunt-ts/tasks/ts.js:318:48
    at next (/Users/xxx/node_modules/grunt-ts/tasks/modules/utils.js:336:23)
    at /Users/xxx/node_modules/grunt-ts/tasks/modules/utils.js:342:9
    at invokeResolver (/Users/xxx/node_modules/es6-promise/dist/commonjs/promise/promise.js:42:5)
    at new Promise (/Users/xxx/node_modules/es6-promise/dist/commonjs/promise/promise.js:29:3)
    at asyncSeries (/Users/xxx/node_modules/grunt-ts/tasks/modules/utils.js:329:12)
```

Actual paths sensored.

Had I knows existance of this parameter earlier I could have debugged more.. :)

**Comment by jounii** [comment]
This is the full grunt config.

```
        // Typescript compiler
		ts: {
			production: {
				src: ['src/ts/main.ts'],
				out: 'src/js/main.js',
				options: {
					module: 'amd',
					target: 'es5',
					sourceMap: false,
					declaration: false,
					noImplicitAny: false,
					comments: false
				}
			},
            watch: {
                src: ['src/ts/**/*.ts'],
                outDir: 'src/js',
                watch: 'src/ts',
                options: {
                    module: 'amd',
                    target: 'es5',
                    sourceMap: true,
                    declaration: false,
                    noImplicitAny: false,
                    comments: true
                }
            },
            // All files separate
            development: {
                src: ['src/ts/**/*.ts'],
                outDir: 'src/js',
                options: {
                    module: 'amd',
                    target: 'es5',
                    sourceMap: true,
                    declaration: false,
                    noImplicitAny: false,
                    comments: true
                }
            }
		},
```

grunt ts:development used as the command to run just the development part. The stacktrace points to line which is executed only if options.watch exists. Added some logging and the options look like this at that point:

```
Running "ts:development" (ts) task
{ warnings: [],
  errors: [],
  watch:
   { src: [ 'src/ts/**/*.ts' ],
     outDir: 'src/js',
     watch: 'src/ts',
     options:
      { module: 'amd',
        target: 'es5',
        sourceMap: true,
        declaration: false,
        noImplicitAny: false,
        comments: true } },
  comments: true,
  declaration: false,
  module: 'amd',
  noImplicitAny: false,
  sourceMap: true,
  target: 'es5',
  CompilationTasks: [ { src: [Object], out: undefined, outDir: 'src/js' } ],
  tsconfig: null,
  removeComments: false,
  fast: 'watch',
  compile: true,
  htmlOutDir: null,
  htmlOutDirFlatten: false,
  htmlModuleTemplate: '<%= filename %>',
  htmlVarTemplate: '<%= ext %>',
  failOnTypeErrors: true,
  emitGruntEvents: false,
  targetName: 'development' }
```

Not sure if this is intended to include all target configuration merged (or something like that?). Seems the options get messed up in optionsResolver.resolveAsync().

**Comment by nycdotnet** [comment]
I suspect it's because you're using `watch` as a target.  `watch` is one of the options we use for grunt-ts that gets passed along to Grunt. https://github.com/TypeStrong/grunt-ts#watch  So Grunt is trying to call indexOf on the object.

Perhaps you could rename it to `w` or `watched` or `live` or something?

**Comment by nycdotnet** [comment]
I created a demo for this and my theory was correct - using `watch` as the target name causes this issue.  Technically, this was a bug that was fixed in 5.0 since `watch` should be settable on the `ts` object to apply to all targets.

I think the best solution is to ban reserved words as target names within grunt-ts - and we should throw a hard error like "The grunt-ts keyword 'watch' cannot be used as a target name." or something, rather than failing in a confusing way that produces GitHub tickets.

@jounii I know that's not awesome to hear, but does that make sense?

**Comment by nycdotnet** [comment]
After looking at this more, I think a warning is more appropriate.  That way if it works, great, if not at least people know why.
These will throw warnings:
'amdloader', 'html', 'htmlOutDir', 'htmlOutDirFlatten', 'reference', 'testExecute', 'tsconfig', 'templateCache', 'vs', 'watch'.
This should be in v5.3.0-beta.5.

**Comment by jounii** [comment]
OK, make sense in that regard. Of course not sure why you would want the options flat on the root object. Many plugins seem to use options property for the default shared options, probably just because of this mix-up with target names. Easy to override target names people use.

I renamed my target now to "watcher".

**Comment by nycdotnet** [comment]
Great.  Yeah we use some options on the target (those above) but most on the options object.  Thanks for the report!

**Comment by nycdotnet** [comment]
This is resolved via a warning in grunt-ts v5.3.0 which was just pushed to npm.  Please comment or re-open if there are any remaining issues.  Thank you for contributing!  You're in the patch notes.

**Comment by noelklein** [comment]
I just ran into the same issue. Had a default target for the build process which does not watch files and a separate target for development that does watch files. The only hint in the console was:

> Warning: pattern.indexOf is not a function Use --force to continue.

I did not get any other warning or error message and renaming 'watch' to 'dev' solved the problem.

**Comment by nycdotnet** [comment]
Are you on latest grunt-ts?

**Comment by noelklein** [comment]
yep, in my package.json: `"grunt-ts": "^5.5.1"`

**Comment by Cdvalencia** [comment]
Thanks! @noelklein

**Comment by nycdotnet** [comment]
What version of node and grunt are you using @Cdvalencia / @noelklein  ?

**Comment by Cdvalencia** [comment]
@nycdotnet 
 "grunt": "~0.4.4",
    "grunt-angular-templates": "^1.0.3",
    "grunt-asset-injector": "^0.1.0",
    "grunt-autoprefixer": "~3.0.4",
    "grunt-build-control": "DaftMonk/grunt-build-control",
    "grunt-concurrent": "~2.2.1",
    "grunt-contrib-clean": "~1.0.0",
    "grunt-contrib-concat": "~1.0.0",
    "grunt-contrib-copy": "~1.0.0",
    "grunt-contrib-cssmin": "~1.0.1",
    "grunt-contrib-htmlmin": "~1.1.0",
    "grunt-contrib-imagemin": "~1.0.0",
    "grunt-contrib-jshint": "^1.0.0",
    "grunt-contrib-less": "^1.2.0",
    "grunt-contrib-uglify": "~1.0.1",
    "grunt-contrib-watch": "~1.0.0",
    "grunt-dom-munger": "^3.4.0",
    "grunt-env": "~0.4.1",
    "grunt-express-server": "~0.5.2",
    "grunt-google-cdn": "~0.4.0",
    "grunt-karma": "~0.12.2",
    "grunt-mocha-test": "~0.12.7",
    "grunt-newer": "~1.1.2",
    "grunt-ng-annotate": "^2.0.1",
    "grunt-node-inspector": "~0.4.1",
    "grunt-nodemon": "~0.4.1",
    "grunt-open": "~0.2.3",
    "grunt-protractor-runner": "^3.0.0",
    "grunt-rev": "~0.1.0",
    "grunt-svgmin": "~3.1.2",
    "grunt-usemin": "~3.1.1",
    "grunt-wiredep": "~2.0.0",

**Comment by nycdotnet** [comment]
@Cdvalencia ty - what node version?

**Comment by Cdvalencia** [comment]
8.1.3
  8.1.2
  7.0.0
  * 4.5.0 (Currently using 64-bit executable)

**Comment by Viveur** [comment]
'Warning: pattern.indexOf is not a function Use --force to continue.' 

Upgrading my version of node (was v6) fixed things for me.
