### ISSUE TITLE
Nested arrays in src fails with message "Visual Studio config issue: {}"

### ISSUE THREAD

**Issue by reflectivecode** [TypeStrong/grunt-ts#323]
Nested arrays in `src` worked fine on `5.3.0-beta.4` and before. I'm getting this error on versions `5.3.2`, `5.3.1`, `5.3.0`, and `5.3.0-beta.6`. All other grunt tasks I've tried support nested arrays in `src`.

The error:

    Running "ts:build" (ts) task
    Visual Studio config issue: {}
    Warning: Task "ts:build" failed. Use --force to continue.

    Aborted due to warnings.

My (now broken) grunt ts:build task:

    ts: {
      build: {
        src: [ [ "src/**/*.ts" ], [ "typings/tsd.d.ts" ] ],
        options: {
          module: "commonjs"
        }
      }
    }

The following (without nested arrays) still works.

    ts: {
      build: {
        src: [ "src/**/*.ts", "typings/tsd.d.ts" ],
        options: {
          module: "commonjs"
        }
      }
    }

**Comment by nycdotnet** [comment]
Hi - sorry about that.  I learn something new about Grunt with every release!  We will fix this in the next patch.  PRs accepted in the meantime.  :-)

**Comment by nycdotnet** [comment]
And thank you for the report!

**Comment by davidparsson** [comment]
One use case where support for this is needed is the following:

    applicationSources: [
      "app/file1.ts",
      "app/file2.ts"
    ],
    ts: {
      app: {
        src: [
          "dependencies.ts",
          "<%= applicationSources %>"
        ],
        dest: "build/app.js"
      }
    }

Grunt expands `<%= applicationSources %>`, turning `src` into this:

    src: [
      "dependencies.ts",
      [
        "app/file1.ts",
        "app/file2.ts"
      ]
    ],

**Comment by nycdotnet** [comment]
Thanks for the additional report.  PRs still accepted - but I haven't had time recently to work on this.
