### ISSUE TITLE
Not compiling VS project

### ISSUE THREAD

**Issue by richwatts** [TypeStrong/grunt-ts#325]
I'm using the VS configuration option - I am adding my .csproj but I get namespace errors and syntax errors when compiling.

The project compiles completely fine via Visual Studio build tools. I need this Grunt task for Continuous Integration. Any guidance would be appreciated.

**Comment by nycdotnet** [comment]
Hi.  Can you run Grunt with the `--verbose` switch and let me know what the command line is that gets passed to tsc?

Also, what version of Visual Studio are you using?

Thanks,

-Steve O

**Comment by richwatts** [comment]
So I have managed to get it working. The project is using the TypeScript 1.4 compiler and it isn't upgradable (large LOB app, best not to ask). So I've pointed the customer compiler property to use this compiler and everything is not working as expected. Sorry to waste your time, but thanks for the response!

**Comment by nycdotnet** [comment]
Oh great.  That's fine!  Glad to hear you're having good luck with grunt-ts now.

I'll close this.
