### ISSUE TITLE
TypeScript 1.8 Beta release

### ISSUE THREAD

**Issue by Gouigouix** [TypeStrong/grunt-ts#327]
You'll create a branch v5.4.0-beta for version 1.8 beta?

**Comment by nycdotnet** [comment]
Yes we will have native support for it in the coming weeks.  In the meantime you can use TypeScript 1.8 with grunt-ts today by editing your package.json with the version number of the beta you want (get from npm) then run npm install.  If you need to pass switches that aren't supported natively yet by grunt-ts, use the additionalFlags option which lets you specify any string to pass to tsc.

**Comment by Gouigouix** [comment]
@nycdotnet Cool, I'll test, pending a grunt-ts of beta ;o)

**Comment by JoshuaKGoldberg** [comment]
Did this ever get released?

**Comment by nycdotnet** [comment]
Hasn't yet.  Slowly working to it.  Use additionalFlags for now as described above and 1.8 should work fine.

**Comment by nycdotnet** [comment]
This is underway in #350.

**Comment by nycdotnet** [comment]
grunt-ts@5.5.0-beta.1 is now on npm with TypeScript 1.8.9 included.

**Comment by Gouigouix** [comment]
Nice ;o)

**Comment by nycdotnet** [comment]
v 5.5 has been published with native support for TypeScript 1.8 switches.
