### ISSUE TITLE
Compile Visual Studio Project file on other OS than Windows

### ISSUE THREAD

**Issue by manfield** [TypeStrong/grunt-ts#345]
TypeScript paths, specified in VS prj file include the Windows' standard path separator "\".
That produce errors on other OS when trying to compile a VS prj file on other OS (like OSX),
Is there any workaround for that? Will it be considered as an issue to be solved in order to increase tool's portability?
Thanks

**Comment by nycdotnet** [comment]
Good call.  This should be fixed in the csproj2ts library.  PRs accepted and I'm actually surprised this hadn't been raised yet.

**Comment by manfield** [comment]
As far as I know a slash is always compatible, even on Windows OS.
We should avoid any OS check and substitute file separators.

**Comment by nycdotnet** [comment]
This should be available in v5.4.0 - just deployed to npm.  Please let me know if you experience further issues.  Thanks for the PR!!!

**Comment by manfield** [comment]
Awesome, thank you for your support.
