### ISSUE TITLE
Compile all *.server.ts files but leave *.client.ts files untouched ?

### ISSUE THREAD

**Issue by daslicht** [TypeStrong/grunt-ts#351]
Hi,
lets say we have the following naming schema of files:

```
main.server.ts
main.client.ts
```
Is it possible to compile to just compile all *.server.ts files and leave the *.client.ts files untouched ?

related:
http://stackoverflow.com/questions/36436676/how-to-compile-all-files-with-the-extension-server-ts-only

**Comment by nycdotnet** [comment]
Consider something like this in your gruntfile:

```javascript
ts: {
  compileClient : {
    src: ["**/*.client.ts", "!node_modules/**/*.ts"]
  },
  compileServer : {
    src: ["**/*.server.ts", "!node_modules/**/*.ts"]
  }
}
```

You'd then be able to run `grunt ts:compileServer` or `grunt ts:compileClient` and it compile the appropriate set of files.  To make Atom leave the files alone, you can disable compile on save - see here: https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave

**Comment by daslicht** [comment]
Uhh Oh thats the missing link. 
```disable compile an save!```

Does that also prevent Atom from showing the warning that the files are missing in the tsconfig ?

eg:
![](https://i.imgur.com/uKGIm2C.png)

My current plan was to use browserify to bundle the client ts files. 
Will Grunt-ts also bundle the imports into one file so that I can use it in the browser? 
How would I have to load them ? 
Do I need a Loader like SystemJS or could I just use them like a browserify bundle?

Thank you !

**Comment by daslicht** [comment]
Just tested : 

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true
    },

    "atom": {
        "rewriteTsconfig": true,
        "buildOnSave": false
    }
}

```
no more compiler warnings :) I am going to try Grunt later when having more time

Thank You !

**Comment by nycdotnet** [comment]
Note: `compileOnSave` under `compilerOptions` is the one you want.  `buildOnSave` defaults to false already.  `compileOnSave` controls "save one .ts file, emit one .js file".  `buildOnSave` controls "save one .ts file, emit **all** the .js files".

**Comment by daslicht** [comment]
Thank you !
