### ISSUE TITLE
Typescript 1.9 and outdir

### ISSUE THREAD

**Issue by pocesar** [TypeStrong/grunt-ts#358]
I'm not being able to compile my server .ts files from one folder (./src) to the ./lib folder. everything is getting compiled alongside the .ts files inside ./src

``` js
        ts: {
            // A specific target
            server: {
                files: [
                    {
                        src: ['typings/generic.d.ts', 'src/server/**/*.ts', 'src/server/*.ts'],
                        dest: './lib'
                    }
                ],
                outDir: './lib'
            },
            options: {
                fast: 'never',
                newLine: "LF",
                allowJs: true,
                pretty: true,
                target: 'es5',
                preserveConstEnums: true,
                module: 'commonjs',
                sourceRoot: './src',
                declaration: false,
                removeComments: false,
                moduleResolution: "node",
                noResolve: false,
                noImplicitAny: true,
                inlineSourceMap: true
            }
        },
```

doesn't matter if I use `outDir` or not, if I use `src` and `outDir` instead of  `files`. this very same configuration used to work fine before I needed 1.9 features

grunt 1.0.1, grunt-ts 5.5.1, tsc v1.9.0-dev.20160530-1.0, node 6.2.0 x64

btw, my tsconfig.json can't be used, as it's configured to work with vscode only:

``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "preserveConstEnums": true,
        "pretty": true,
        "allowJs": true,
        "moduleResolution": "node",
        "target": "es5"
    },
    "exclude": [
        "lib",
        "data",
        "config",
        ".vscode",
        ".tscache",
        "typings",
        "node_modules",
        "tests",
        "conf",
        "keys",
        ".sass-cache",
        "views",
        "public"
    ]
}
```

**Comment by pocesar** [comment]
Playing around with settings, oddly enough, only half of the files get compiled in lib:

```js
            server: {
                src: [
                    'typings/generic.d.ts',
                    'src/server/**/*.ts',
                    'src/server/*.ts'
                ],
                outDir: 'lib',
                options: {
                    fast: 'never',
                    module: "commonjs",
                    noImplicitAny: true,
                    removeComments: false,
                    preserveConstEnums: true,
                    inlineSourceMap: true,
                    sourceMap: false,
                    rootDir: "src",
                    pretty: true,
                    newLine: "LF",
                    //allowJs: true,
                    moduleResolution: "node",
                    target: "es5",
                    declaration: false
                }
            },
```

only those files are created in `lib` folder: 

```
lib/server/app.js
lib/server/modules/formula.js
lib/server/pages/user/index.js
lib/server/pages/admin/index.js
```

those are created in `src` folder:

```
src/server/models/admin.js
src/server/models/user.js
src/server/modules/common.js
src/shared/cnpj.js
src/shared/definitions.js
src/shared/validation.js
src/shared/venda.js
```

**Comment by robpaveza** [comment]
I'm seeing the same problem.  The entirety of my grunt ts setting is to load my tsconfig.json.  If I `tsc` in that folder, everything works fine.  If I `grunt ts:default` in that folder, it's as if it `cd lib && tsc` there.

    {
        "compilerOptions": {
            "module": "commonjs",
            "removeComments": false,
            "sourceMap": true,
            "target": "ES6",
            "allowJs": true,
            "outDir": "../tmp",
            "noResolve": true
        },
        "exclude": [
            "node_modules",
            "dist",
            "tools",
            "index.js",
            "bin"
        ],
        "compileOnSave": true
    }

From my Gruntfile:

        ts: {
            default: {
                tsconfig: './tsconfig.json',
                options: {
                    verbose: true
                }
            }
        }
