### ISSUE TITLE
warning about deprecated lodash-dependency

### ISSUE THREAD

**Issue by andersmollmark** [TypeStrong/grunt-ts#359]
Hi, I get warnings about the use of a deprecated version of lodash.

npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

Is this something that can be fixed?
I am using the latest v 5.5.1 of grunt-ts.

**Comment by nycdotnet** [comment]
Yes - feel free to upgrade the dependency, run the tests and submit a PR.  There may be some lodash plugin dependencies to sort through as well. I haven't done this yet because the version we have works ok for our needs and there are some higher-priority issues.  Thanks!

**Comment by alisabzevari** [comment]
@andersmollmark You can close this issue. The version has been upgraded.

**Comment by nycdotnet** [comment]
thanks
