### ISSUE TITLE
grunt-ts's module doesn't support 'commonjs'

### ISSUE THREAD

**Issue by zzsanduo** [TypeStrong/grunt-ts#361]
Hi,
The readme said, the 'module' property of grunt-ts module can be set either 'amd' or 'commonjs'. When I set it as 'commonjs' in my Gruntfile.js, I met the error 
     error TS6082: Only 'amd' and 'system' modules are supported alongside --out.

Is there any problem with my config or is the readme not updated? 

Thanks.

**Comment by nycdotnet** [comment]
The TypeScript compiler doesn't support concatenating CommonJS modules.  If you want to concatenate that style of module, you have to use a tool like Webpack or Browserify.  AMD modules and modules in the System.register format are much simpler to concatenate, so support for that is built-in to TypeScript.

Thanks for bringing this up.  I'll accept a PR for the docs.

**Comment by nycdotnet** [comment]
Thank you for the PR @zzsanduo !  You're mentioned in the CHANGELOG file.

**Comment by Durisvk** [comment]
That's totally wrong. You say I should use your concurrency? You don't even care? Ok I am going to use Webpack and I'll never use Grunt ever...
