### ISSUE TITLE
How to declare which typings are needed

### ISSUE THREAD

**Issue by ooxi** [TypeStrong/grunt-ts#373]
Does this plugin come with support for typings or do I need a plugin like [grunt-typings](https://www.npmjs.com/package/grunt-typings)?

**Comment by nycdotnet** [comment]
Grunt-ts has no direct support to fetch TypeScript definition files - it's for compilation only.  If you have d.ts files downloaded (with typings, tsd, or manually), grunt-ts will find them and have TypeScript compile them assuming your referenced tsconfig.json or the src glob includes them.

**Comment by nycdotnet** [comment]
To answer your other question, yeah perhaps grunt-typings is what you want if you need typings files to be downloaded automatically as part of a CI process.

**Comment by ooxi** [comment]
Thanks for your feedback! I ended up using `grunt-typings` for fetching required typings and `grunt-ts` for actual compilation.

What I missed at first was the grunt-ts [tsconfig setting](https://www.npmjs.com/package/grunt-ts#tsconfig). Without that setting the TypeScript compiler didn't seam to understand where the project was located and thus did not recognize the type definitions downloaded by `grunt-typings`.

**Comment by nycdotnet** [comment]
Great - good luck with TypeScript!
