### ISSUE TITLE
Compile is Overly Greedy

### ISSUE THREAD

**Issue by steenbag** [TypeStrong/grunt-ts#374]
Hi there; just getting into TypeScript, but running into a roadblock while trying to get up and running. Not sure if it is a config issue or what:

My grunt config:
`ts: {
      default: {
        tsconfig: true,
        src: ['app/assets/scripts/**/*.ts', '!node_modules/**', '!vendor/**', '!app/assets/vendor**'],
        outDir: 'app/storage/assets/scripts/',
        options: {
          verbose: true,
          rootDir: "./app/assets/scripts"
        }
      }
    },`

I have a single .ts file located at app/assets/scripts/tasks/test.ts. So according to the globbing pattern, this is the only file that should be compiled, however the output is as follows:
<img width="1513" alt="screen shot 2016-08-23 at 10 58 10 pm" src="https://cloud.githubusercontent.com/assets/3892878/17916918/7ff0cc5a-6985-11e6-8e38-2857c529ad23.png">
As you can see it's capturing all sorts of stuff within vendor, and app/assets/vendor which should be excluded based on the pattern. The only way I can get a successful build is to add 
`"exclude": [
    "node_modules",
    "vendor",
    "app/assets/vendor"
  ]`
to tsconfig.json. Shouldn't the glob pattern be honored?

Thanks, loving TypeScript so far, I'm sure I just have something setup wrong.

**Comment by nycdotnet** [comment]
Welcome to TypeScript!

The tsconfig.json integration of grunt-ts is a bit complex for historical reasons.  If you are using an editor that has TypeScript language service integration, it may be best for you to not use a `src` glob with grunt-ts and just have grunt-ts get its config from your `tsconfig.json file`.  In this case, you'd use the `exclude` functionality of the `tsconfig.json`.  This would enable you to keep your configuration in one place.

If after reading this section of the docs very carefully, you think that grunt-ts is not working as documented, please let me know and I'll take a look.  https://github.com/TypeStrong/grunt-ts#tsconfig

If you're still not clear, please provide the contents of your `tsconfig.json` file.  Thanks.

**Comment by nycdotnet** [comment]
Hi - since I didn't hear back, I am going to close this out. Please let me know if you still think there is a problem with the latest version.  Thanks.
