### ISSUE TITLE
UpdateFiles (tsconfig) Without Building 

### ISSUE THREAD

**Issue by RyanThomas73** [TypeStrong/grunt-ts#375]
I'm working on the setup for a new project using tsc 2.0.3.  My actual build process is being done with webpack and the ts-loader plugin. I'm using atom-typescript and I rely on the rewriteTsconfig: true value to automatically update my files based on my globbing patterns.

I would like to include grunt-ts as a backup to ensure that the build pipeline has the correct files listed in the tsconfig.json. It would also provide an option for future teammates that aren't using atom to automatically update the tsconfig files. 

I'm using the baseUrl and paths features of typescript 2.0. Since these features aren't currently supported by grunt-ts ( #339 ) the build fails and I would have to use a --force command to continue with the rest of my build pipeline. I can use passthrough to get the grunt-ts task to successfully build but doing so doesn't execute the updateFiles logic. 

It would be nice to be able to execute the tsconfig updateFiles logic as a standalone feature of grunt ts without attempting to build.

**Comment by nycdotnet** [comment]
Can you set the `compile` option to false?

**Comment by RyanThomas73** [comment]
Yes and it behaves as expected.

#facepalm
