### ISSUE TITLE
Making use of --outFile generates a single output js file with named modules, but js extension missing

### ISSUE THREAD

**Issue by akhilesh84** [TypeStrong/grunt-ts#382]
Hi,

Not sure if this was asked/raised earlier in this forum or not.

I am using the _--outFile_ compile option to generate a single JS file as the output of the build step. It works fine. The file does get generated with a number of modules do getting registered using System.register.

The issue comes when the app gets bootstrapped. The file gets downloaded but is not executed. This happens because the name of the module registered has the extension (.js) missing. i.e., the module name should have been "app/configs/baseConfig.js" instead of "app/configs/baseConfig" and "app/configs/dev.js" instead of "app/configs/dev".

```
System.register("app/configs/baseConfig", [], function(exports_2, context_2) {
    "use strict";
    var __moduleName = context_2 && context_2.id;
    var ConfigBase;
    return {
        setters:[],
        execute: function() {
            ConfigBase = (function () {
                function ConfigBase() {
                    this.searchUISettings = {
                        title: 'SOME_SETTINGS'
                    };
                }
                return ConfigBase;
            }());
            exports_2("ConfigBase", ConfigBase);
        }
    }
});

System.register("app/configs/dev", ["app/configs/baseConfig"], function(exports_3, context_3) {
    "use strict";
    var __moduleName = context_3 && context_3.id;
    var baseConfig_1;
    var Config, CONFIG;
    return {
        setters:[
            function (baseConfig_1_1) {
                baseConfig_1 = baseConfig_1_1;
            }],
        execute: function() {
            Config = (function (_super) {
                __extends(Config, _super);
                function Config() {
                    _super.apply(this, arguments);
                    this.ptisearchwebapi = {
                        baseUrl: '/SymbolStore/api'
                    };
                }
                return Config;
            }(baseConfig_1.ConfigBase));
            exports_3("Config", Config);
            exports_3("CONFIG", CONFIG = new Config());
        }
    }
});
```

Does it have anything to do with my systemjs configuraton? Here is what I have there:

```
meta['app/*'] = {
        format: 'register'
    };
    packages['app'] = { main: 'main', defaultExtension: 'js' };
```

**Comment by nycdotnet** [comment]
Hi there,

I am sorry it took so long to reply to you.  A few things: There has been talk of allowing TypeScript to ignore .js on import statements as long as there is a .ts file in the same relative path.  I'm not sure if that's already been implemented, but if it hasn't been yet, it's likely coming.

The other thing is that you can use `defaultJSExtensions: true`  (note this is slightly different than what you have) which is technically a deprecated flag for System.js, but will automatically add the .js if there is no extension at all specified.  It's been deprecated for a few years now, so I can't imagine they're in a rush to remove it.

An example call:
```js
System.config({
    map: {
        'jquery': '/scripts/jquery/jquery.min.js'
    },
    defaultJSExtensions: true
});
```


I hope that helps and this is not vastly too late.  I am going to close this out, but please reopen if
