### ISSUE TITLE
skipLibCheck compiler option is not supported by this plugin

### ISSUE THREAD

**Issue by wcarmon** [TypeStrong/grunt-ts#385]
The "skipLibCheck" option is missing.
https://www.typescriptlang.org/docs/handbook/compiler-options.html

One might expect it to be referenced around here: 
https://github.com/TypeStrong/grunt-ts/blob/v5.5.1/tasks/modules/compile.ts#L263

**Comment by nycdotnet** [comment]
Hello, wcarmon.  For the moment you can use this (or any relatively new switch) via the additionalFlags feature.

https://github.com/TypeStrong/grunt-ts#additionalflags

Pull requests always accepted.  Thanks.

**Comment by nycdotnet** [comment]
This is implemented in 6.0.0-beta.6 on npm.  Please give it a whirl and let me know if you hit any issues.

**Comment by nycdotnet** [comment]
I am going to close this issue as I believe it is resolved in the latest beta.  Please feel free to reopen/comment.  Thank you!
