### ISSUE TITLE
Compiler option 'out' expects an argument

### ISSUE THREAD

**Issue by rjmacarthy** [TypeStrong/grunt-ts#386]
```
Running "ts:dev" (ts) task
Compiling...
Using tsc v1.8.9
error TS6044: Compiler option 'out' expects an argument.
>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 1
Warning: Task "ts:dev" failed. Use --force to continue.
Aborted due to warnings.
```

Why can I not specify a blank `outFile` parameter or not specify one at all?

I need to compile the js and js.map files inline with the ts files rather than creating one dist file. 

Thanks.

**Comment by nycdotnet** [comment]
Grunt-ts is just mapping the values you specified.  If you don't want to use outFile, just don't specify it at all and grunt-ts won't try to pass it to tsc.  Hope that helps.

**Comment by rjmacarthy** [comment]
Thank you for your reply, much appreciated. But not specifying an `out` or `outFile` parameter doesn't seem to work?

Here is my tsconfig file

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "amd",
        "moduleResolution": "classic",
        "sourceMap": true,
        "jsx": "preserve"
    },

    "exclude": [
        "node_modules",
        "typings/browser",
        "typings/browser.d.ts",
        "Scripts/typings/"

    ],
    "buildOnSave": false,
    "compileOnSave": true
}
```

And here is my gruntFile configuration for grunt-ts.
```
 dev: {
                 tsconfig: './tsconfig.json',
                 options: {
                     compile: true,
                     target: 'es5',
                     module: 'amd',
                     sourceMap: true,
                     verbose: false,
                     declaration: false,
                     jsx: 'react',
                     fast: 'never',
                     moduleResolution: "classic"
                 },
                 vs: 'TypeScriptApp.csproj'
             }
```

As you can see no out or outFile parameter is specified but I still get the error:

```
Running "ts:dev" (ts) task
Compiling...
WARNING: TypeScript does not allow external modules to be concatenated with --out. Any exported code may be truncated.  See TypeScript issue #1544 for more details.
Using tsc v1.8.9
error TS6044: Compiler option 'out' expects an argument.
>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 1
Warning: Task "ts:dev" failed. Use --force to continue.
Aborted due to warnings.
```

Any ideas?

Thanks.

**Comment by nycdotnet** [comment]
I suspect you have out specified in your .csproj file.  Right click your solution and open the TypeScript build properties.  Change it for both Release and Debug (or any other build configs you use) to not use out.

**Comment by rjmacarthy** [comment]
Absolute legend!  

That worked, thank you very much.

Just as an extra, I removed tsconfig.js from the grunt config aswell.

Thanks.

Richard.

**Comment by nycdotnet** [comment]
I'm glad I could be of assistance.
