### ISSUE TITLE
Suppress console output for compiled files

### ISSUE THREAD

**Issue by maninak** [TypeStrong/grunt-ts#389]
Hi, I don't seem to find any option to not show the compilation message that is printed in the console **for each** single ts file that has been compiled. I am refering to messages like this:

`### Fast Compile >>src/server.ts`

In a project running under watch to recompile after each saved change, this is spammy and too verbose. When the count of ts files increases this quickly gets out of hand.

Is there an option/flag I'm missing here? If not, I think this is a feature sorely needed.

Thank you for your time.

**Comment by nycdotnet** [comment]
Hi - you're not missing it.  PRs definitely accepted to add such a feature.  Feel free to comment out the line that is writing that message to the console.

**Comment by maninak** [comment]
For anyone searching for a quick solution to this until we have a proper fix:

1. In your `package.json` scripts, add this new entry `"postinstall": "scripts/postinstall.sh",`
2. Then (if you don't already have it), in your root project directory create a folder `scripts` and within it a file `postinstall.sh`
3. paste the following code inside the file
```
#!/bin/sh

# Removes spammy console.log for each single compiled file by grunt-ts package
sed -i "s/^.*### Fast Compile.*$//" node_modules/grunt-ts/tasks/modules/compile.js
``` 

With this, it is ensured that whenever you `npm install` the line is removed from grunt-ts source code.

**Comment by nycdotnet** [comment]
I am just going to remove this in grunt-ts 6.  There is a new switch called `listEmittedFiles` that can be used if people want this behavior.  Thanks for the report.

**Comment by shmax** [comment]
Any ETA on a release for this feature? It causes some trouble in Jetbrains IDEs due to a bug of their own:

https://youtrack.jetbrains.com/issue/WEB-31017

**Comment by nycdotnet** [comment]
Hi @shmax - I haven’t been able to spend much time on grunt-ts lately but PRs definitely accepted if you are willing.
