### ISSUE TITLE
Issue with "WARNING: TypeScript < 1.8 does not allow....."

### ISSUE THREAD

**Issue by blendsdk** [TypeStrong/grunt-ts#395]
Hi,

I am trying to run grunt-ts on several files which I need to have concatenated at the end.
I have set the module to "amd" but I get the warning anyway!

I create a config by the following helper function. 

```javascript
function createTypeScriptBuild(outfile, sourceMap, genDeclaration, files) {
    var config = { files: [] };
    sourceMap = sourceMap || false;
    genDeclaration = genDeclaration || false;
    config.options = {
        compiler: './node_modules/typescript/bin/tsc',
        module: 'amd',
        inlineSourceMap: sourceMap,
        inlineSources: sourceMap,
        noImplicitAny: true,
        declaration: genDeclaration,
    };
    config.files.push({
        src: files,
        dest: outfile
    })
    return config;
}
```

Am i doing something wrong?

**Comment by nycdotnet** [comment]
What version of TypeScript are you using and are you getting the expected result other than the warning?

**Comment by blendsdk** [comment]
I am using the following:

```javascript
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-contrib-clean": "^1.0.0",
    "grunt-sass": "^2.0.0",
    "grunt-ts": "^6.0.0-beta.11",
    "typescript": "^2.1.5"
  }
````
And it produces the correct result (for now at least)

**Comment by nycdotnet** [comment]
The reason for this is that you're using a custom compiler.  I'm going to see if I can just not send the error in this case.  Thank you for the report!

**Comment by nycdotnet** [comment]
Would you please test again with grunt-ts@6.0.0-beta.14 which has just been published?

Thank you.

**Comment by blendsdk** [comment]
Works like a charm. Thank you

**Comment by nycdotnet** [comment]
Thank you for for the report!
