### ISSUE TITLE
Getting typing warnings left and right

### ISSUE THREAD

**Issue by CarlosAmaral** [TypeStrong/grunt-ts#396]
![screenshot_39](https://cloud.githubusercontent.com/assets/12385793/22883103/6e27aec8-f1e6-11e6-90a6-c64bad2e6350.png)

Tried to change the `tsconfig.json` file but can't run this module without getting the warnings above. It does compile but can't get rid of those typings warnings. I've tried inserting: `reference": "typings/index.d.ts"` to point to the references file but no luck. Thanks.

**Comment by nycdotnet** [comment]
What version of TypeScript does grunt-ts report it is using?  Is that the expected version?  Are you using a tsconfig.json file in your editor?  If so, does it compile without errors?  If so, have you tried referencing the tsconfig file in the config object for grunt-ts?

Sorry for brevity- typing on mobile.

**Comment by CarlosAmaral** [comment]
Typescript version is 2.1.4

Yes, im using a tsconfig.json like this: 
`{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "typeRoots": [
            "../node_modules/@types"
        ],
        "types" : [
            "angular"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
`

and my grunt ts task is:
`
ts: {
            default: {
                src: ["public/www/app/**/**/*.ts"],
                watch: ".",
                reference: "typings/index.d.ts"
            }
        },`

> ? If so, have you tried referencing the tsconfig file in the config object for grunt-ts?
Don't think so, not sure how it's meant to be done.

**Comment by nycdotnet** [comment]
Docs here:

https://github.com/TypeStrong/grunt-ts#tsconfig

Try this for your ts section to see if it builds as expected (replace the path with the correct relative path from the Gruntfile.js to your tsconfig.json file).  If so, that's the best way to do it.  Any other options you specify in the Gruntfile will override what's in your tsconfig.

```
ts: {
            default: {
                tsconfig: "./tsconfig.json"
            }
        },
```

**Comment by CarlosAmaral** [comment]
It worked. Thanks.

**Comment by nycdotnet** [comment]
No worries.
