### ISSUE TITLE
Cannot exclude file 

### ISSUE THREAD

**Issue by mike123vn** [TypeStrong/grunt-ts#401]
I cannot exclude compile  file even I put this file with ! in Gruntfile
I'm using newest version of typescript 2.2.2  and grunts 6.0.0-beta.15
```

module.exports = function (grunt) {
    grunt.initConfig({
        ts: {
            default: {
                src: ['**/*.ts',
                    '!page_fragments/element_types.pfrag.ts',
                    '!node_modules/**/*.ts']
            },
            options: {
                target: "es5",
            }
        }
    });
    grunt.loadNpmTasks("grunt-ts");
    grunt.registerTask("default", ["ts"]);
};
```

**Comment by nycdotnet** [comment]
I just created a repo to investigate this issue, and it appears to work as expected for me.

https://github.com/nycdotnet/grunt-ts-401/

When running grunt, the file `app/myapp.ts` gets compiled, but the file `page_fragments/element_types.pfrag.ts` does not.  Does it work differently for you?
