### ISSUE TITLE
option "fast: never" ignored and libs not well formed transmit to tsc

### ISSUE THREAD

**Issue by ChristophAtAdlos** [TypeStrong/grunt-ts#406]
I try to improve the watch build speed by compile only the changed files.  I have a watch task which calls the `ts:single` task to compile a single changed file. The configuration is just identical with the tscionfig.json.
Compiled by the tsconfig.json, all works fine `ts:build`. But with the `ts:single` task, I receive some errors.   

This is my grunt-ts config:   
```javascript
        ts: {
            build: {  // runs tsc once by tsconfig.json
                tsconfig: {
                    tsconfig: path.resolve("tsconfig.json"),
                    passThrough: true
                }
            },
            single: { // must be run by watch task, "files" injected by onWatch event
                files: [
                    {
                        src: "",
                        dest: ""
                    }
                ],
                options: {
                    alwaysStrict: true,
                    baseUrl: ".",
                    declaration: false,
                    emitDecoratorMetadata: true,
                    experimentalDecorators: true,
                    typeRoots: ["node_modules/@types"],
                    moduleResolution: "node",
                    target: "es5",
                    lib: ["es2015", "dom"],
                    skipDefaultLibCheck: true,
                    module: "umd",
                    noImplicitAny: false,
                    removeComments: false,
                    preserveConstEnums: true,
                    sourceMap: false,
                    allowJs: false,
                    outDir: "temp/",
                    rootDir: "src/",
                    fast: "never",
                    passThrough: true,
                    verbose: true
                }
            }
        },
```

**The output when changed a file:**   

```javascript
Running "watch:ts" (watch) task
Waiting...
processing watched files: ["src\\WebTest\\databrowser.ts"] 

WATCH: onChange by changed
new files config for  ts :
[
	{
		"src": "src\\WebTest\\databrowser.ts",
		"dest": "build/WebTest/"
	}
]
>> File "src\WebTest\databrowser.ts" changed.

Running "ts:single" (ts) task
Warning: target "single" is attempting to use fast compilation with "files".  This is not currently supported.  Setting "fast" to "never".
Watching all TypeScript / Html files under : .
Compiling...
Using tsc v2.3.0
src\WebTest\databrowser.ts --emitDecoratorMetadata --preserveConstEnums --experimentalDecorators --moduleResolution node --rootDir src/ --skipDefaultLibCheck --alwaysStrict --baseUrl  --lib es2015,dom --typeRoots "node_modules/@types" --target ES5 --module umd --outDir build/WebTest/testing/
error TS6053: File 'es2015,dom.ts' not found.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
```

**There are two errors:**  

1. The defined `fast: 'never'` is ignored and I receive a message to set this property I already set...

  Why is this ignored? I checked the typo really.

2. The defined libs are joined to `--lib es2015,dom` for the tsc which understands `es2015,dom.ts` instead of `lib.es2015.d.ts, lib.dom.d.ts`. The `,` seems to been treated as part of the string...

  Is there an error in my config, or is this a grunt-ts bug or a tsc bug?

**Versions**   
grunt: 0.4.5   
grunt-ts: 6.0.0.-beta.16   
typescript: 2.3.0   

**What I tried**   
grunt-ts: 5.1.1 downgrade   

Now, I don't receive an error message concerning the libs, but the libs are not loaded, I receive now all this TS2693 errors which comes when the libs aren't loaded. 

Any idea?

**Comment by claudiuconstantin** [comment]
Remove the comma, it should be `--lib es2015 dom`

**Comment by ChristophAtAdlos** [comment]
This means, it's an grunt-ts error, since it's grunt-ts who transforms from `lib: ["es2015", "dom"]` to `--lib es2015,dom`.

**Comment by nycdotnet** [comment]
Thank you for the report, @ChristophAtAdlos, and the tip, @claudiuconstantin .  I have just verified that grunt-ts is concatenating the lib options correctly with a comma and no space and that this works as expected in both TypeScript 2.1.6 and 2.4.2.

For example, in a new folder with just `npm install typescript@2.1` or `npm install typescript@latest`, and a file `a.ts`, the following command compiles successfully:  `node node_modules/typescript/lib/tsc.js --lib es2015,dom a.ts`

I'm wondering if the problem is the baseUrl which doesn't seem to be putting a value in the output.

**Comment by nycdotnet** [comment]
@ChristophAtAdlos Do me a favor: Can you edit the `tasks/modules/utils.js` file inside your downloaded grunt-ts package, and update the `possiblyQuotedRelativePath` function (around line 75) to this:

```
function possiblyQuotedRelativePath(thePath, relativeTo) {
    if (relativeTo === void 0) { relativeTo = '.'; }
    var result = enclosePathInQuotesIfRequired(path.relative(relativeTo, path.resolve(thePath)));
    return result === "" ? "." : result;
}
```

And let me know if that fixes it for you.  You could also just probably skip specifying the `baseUrl`, as I think the `.` value is implied.

**Comment by ChristophAtAdlos** [comment]
grunt-ts: 6.0.0-beta.16, with umd as "module":

```
Running "ts:single" (ts) task
Warning: target "single" is attempting to use fast compilation with "files".  This is not currently supported.  Setting "fast" to "never".
Compiling...
Using tsc v2.3.4
WARNING: TypeScript 1.8+ requires "module" to be set tosystem or amd for concatenation of external modules to work.
src\app\websocket.ts --emitDecoratorMetadata --preserveConstEnums --experimentalDecorators --moduleResolution node --rootDir src/ --skipDefaultLibCheck --alwaysStrict --baseUrl . --lib es2015,dom --typeRoots "node_modules/@types" --target ES5 --module umd --out temp/app/websocket.js
error TS6082: Only 'amd' and 'system' modules are supported alongside --out.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:single" failed. Use --force to continue.

Aborted due to warnings.
```
This error message is much clearer then the old above...

with amd as "module":
```
"C:\Program Files\JetBrains\WebStorm 2017.1.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Git\Easystick\PAI041.Backend\node_modules\grunt-cli\bin\grunt --gruntfile C:\Git\Easystick\PAI041.Backend\Gruntfile.js ts:single
Running "ts:single" (ts) task
Warning: target "single" is attempting to use fast compilation with "files".  This is not currently supported.  Setting "fast" to "never".
Compiling...
Using tsc v2.3.4
src\app\websocket.ts --emitDecoratorMetadata --preserveConstEnums --experimentalDecorators --moduleResolution node --rootDir src/ --skipDefaultLibCheck --alwaysStrict --baseUrl . --lib es2015,dom --typeRoots "node_modules/@types" --target ES5 --module amd --out temp/app/websocket.js



TypeScript compilation complete: 2.48s for 1 TypeScript files.

Done, without errors.
```

We can't switch to amd/system, it's a requirement. The configuration above is identical with the working tsconfig.json. Why does this work with the tsconfig.json, but not by grunt-ts?


Why do I get the "fast"->"never" error when fast is set correctly?

**Comment by ChristophAtAdlos** [comment]
Changed the config to:
```
[...]
            single: {
                src: [
                    "src/app/myFile.ts"
                ],
[...]
```

Now I don't get errors, but the file is compiled in place, not to the defined outDir "temp/".

How can I compile the file to a specific place with "umd" as "module"?

**Comment by ChristophAtAdlos** [comment]
Concerning your `possiblyQuotedRelativePath` function patch...   

After having changed from `files` to `src` in the `single` target:   

- With your code, I don't get an error if basePath is specified as ".".
- Without your code, I don't get an error if basePath is NOT specified.

**Comment by ChristophAtAdlos** [comment]
Ok, now, I found how to get the outDir in the command line:   

Other than in tsconfig, grunt-ts needs outDir to be defined in the `files` section, not in `options`:

```
[...]
            single: {
                src: [
                    "src/app/myFile.ts"
                ],
                outDir: "temp/",
[...]
```
This works, but tsc compiles all ts files underneath src and not only this one specified by `src`. :-(

**Comment by nycdotnet** [comment]
Take a look here:  https://github.com/TypeStrong/grunt-ts#files

The pattern you probably want to emulate is `compileTwoSetsOfFilesToDirUsingArrayStyle`, but you will only do one set of files.  Some logic is applied to the `dest` property to try to infer if it's a directory or a file, so it should work for you.

**Comment by nycdotnet** [comment]
Also thank you for confirming the fix on that function.  I will try to get it patched soon.  I think you don't have to pass it in your case.  baseDir = "." is the default case anyway.

**Comment by ChristophAtAdlos** [comment]
Thank you! It work's now for me.
It seems that tsc (when called on the command line) compiles all imported/required modules/files.  
The only way to speed up seems to be: use tsc's own watch and not the grunt ones...
