### ISSUE TITLE
TS 2.3 flags (eg downlevelIteration flag) are not supported

### ISSUE THREAD

**Issue by dhedey** [TypeStrong/grunt-ts#410]
See https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md for the flag.

Requires an addition to propertiesFromTargetOptions here:
https://github.com/TypeStrong/grunt-ts/blob/master/tasks/modules/optionsResolver.ts

**Comment by dhedey** [comment]
My apologies, I failed to read https://github.com/TypeStrong/grunt-ts/blob/master/CONTRIBUTING.md and failed to notice the Typescript 2.3 branch 👍 .

Look forward to seeing these features live! Thanks for the hard work on this!

**Comment by nycdotnet** [comment]
I'm slow :-(  Thanks for the kind feedback, though!
