### ISSUE TITLE
ts task not using task options

### ISSUE THREAD

**Issue by kierans** [TypeStrong/grunt-ts#412]
It appears that trying to use Grunt's ability to define task level options doesn't work.  By defining multiple targets in my config, I have to specify the same options eg:

```javascript
ts: {
  options: {
    // does not work, tsconfig never used.
    tsconfig: true
  },
  src: {
    src: [ "src/**/*.ts" ],
    // if not present, tsconfig.json not used where as task level options has defined the option
    tsconfig: true
  },
  test: {
    src: [ "test/**/*.ts" ],
    // if not present, tsconfig.json not used
    tsconfig: true
  }
}
```
Running `grunt -v ts:src` shows me the use of my `tsconfig.json` (or not) to `tsc` based on the above config and commenting/toggleing the use of the `tsconfig` property.

**Comment by nycdotnet** [comment]
Thanks for contributing.  `tsconfig` doesn't go under options.  Please see [this table](https://github.com/TypeStrong/grunt-ts#grunt-ts-gruntfilejs-options) which documents which things go where.  Does this work?

```
ts: {
  tsconfig: true,
  options: {
    // items that are listed as options go here.
  },
}
```

**Comment by kierans** [comment]
Thanks @nycdotnet for the help. It does indeed solve my problem.

However as a newbie to your task, not having task options in the `options` block was quite confusing, given that's how Grunt is designed.

**Comment by nycdotnet** [comment]
I understand.  When grunt-ts was first put together some decisions were made that maybe weren’t the best in retrospect, but at this stage of the project we have to keep things as they are.  Glad that worked for you.  There are warnings in place for some options being in the wrong spot - I’m surprised you didn’t get one.  Thanks for contributing.

**Comment by kierans** [comment]
👍
