### ISSUE TITLE
Support skipLibCheck flag

### ISSUE THREAD

**Issue by kierans** [TypeStrong/grunt-ts#413]
When [translating options](https://github.com/TypeStrong/grunt-ts/blob/master/tasks/modules/compile.ts#L285) to `tsc` switches, `skipLibCheck` is missing (`skipDefaultLibCheck` is present however).

**Comment by nycdotnet** [comment]
Thanks for the report.  Will resolve in next release.

**Comment by nycdotnet** [comment]
Should be fixed in v6.0.0-beta.17.  Thanks for the report.
