### ISSUE TITLE
grunt-ts hangs forever

### ISSUE THREAD

**Issue by henck** [TypeStrong/grunt-ts#417]
`grunt-ts` (5.5.1 stable) hangs forever when executed. It produces no output or errors, not even when the `verbose` option is specified. The configuration is the minimalist one:

    module.exports = function(grunt) {
      grunt.initConfig({
        ts: {
          default : {
            src: ["**/*.ts", "!node_modules/**"]
          }
        }
      });
      grunt.loadNpmTasks("grunt-ts");
      grunt.registerTask("default", ["ts"]);
    };

The alternative `grunt-typescript` module works correctly, so I believe required dependencies were correctly installed. `node.js` was installed today (Dec 4, '17), including `npm` (updated with `-g`).

What can I do to find out what's wrong?

**Comment by nycdotnet** [comment]
Hi @henck - sorry for the trouble.  Did you happen to try the latest beta?

**Comment by henck** [comment]
Hello @nycdotnet,

I've installed `grunt-ts-6.0.0-beta.19` and I'm happy to report that it no longer hangs.

**Comment by nycdotnet** [comment]
@henck great.  Is it working OK for you?  I am going to remove the beta tag in the next week or so.  Thank you.
