### ISSUE TITLE
Need to support grunt v1.0.2

### ISSUE THREAD

**Issue by danielrentz** [TypeStrong/grunt-ts#430]
For some reason, I am forced to use grunt v1.0.2 in the project I am working on. I want to introduce TS and grunt-ts in this project. Everything works like a charm, the only problem is the peer dependency `"grunt": "^1.0.3 || ^0.4.0"` which triggers an error when installing the packages in our CI pipeline.

Would it be possible to lower the version to 1.0.2 or even 1.0.0?

**Comment by danielrentz** [comment]
#431

**Comment by nycdotnet** [comment]
Merged.  Thanks for the contribution.  I will try to get a release out later tonight.

**Comment by danielrentz** [comment]
> Merged. Thanks for the contribution. I will try to get a release out later tonight.

Can you tell when the next release might be there?

**Comment by nycdotnet** [comment]
OK this is published as `grunt-ts@6.0.0-beta.22`.  Thanks for your contribution!  You are mentioned in the changelog.

**Comment by danielrentz** [comment]
Thank you very much!
