### ISSUE TITLE
grunt-ts does not work with empty "types" array in tsconfig.json

### ISSUE THREAD

**Issue by danielrentz** [TypeStrong/grunt-ts#442]
I am using grunt-ts with a project file containing an empty "types" array to not load any type definitions from node_modules (as documented [here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types)).
```
{
    "compilerOptions": {
        "types": []
    }
}
```
Using tsc directly works as expected. But grunt-ts fails with
```
Using tsc v3.7.3
error TS6044: Compiler option 'types' expects an argument.
```
Maybe this is related to (https://github.com/microsoft/TypeScript/issues/18581)?

**Comment by nycdotnet** [comment]
hi - the best way around this is to use the tsconfig.json integration with passThrough turned on.  In this mode, grunt-ts just calls TypeScript and lets it handle the rest.

```
grunt.initConfig({
  ts: {
    default: {
      // specifying tsconfig as an object allows detailed configuration overrides...
      tsconfig: {
        tsconfig: './sometsconfig.json',
        passThrough: true
      }
    }
  }
});
```

**Comment by danielrentz** [comment]
Thanks for this hint!
