### ISSUE TITLE
Take over as maintainer

### ISSUE THREAD

**Issue by donatj** [TypeStrong/grunt-ts#456]
Hey @nycdotnet - I messaged you on Twitter but it appears you may no longer be active there.

I would be interested in taking over as a maintainer on grunt-ts.

**Comment by kmgdevelopment** [comment]
@nycdotnet Would love to see this handed off to someone who can keep it maintained!

**Comment by donatj** [comment]
We moved off grunt - actually largely motivated by the lack of maintenance on this package. 

My interest in maintaining it has waned as such.

I would have also loved to have seen this given to someone willing though. Would have been cool if I'd at least gotten a "no" though 😆

**Comment by kmgdevelopment** [comment]
@donatj Yeah, I was able just now to get a better working setup using `grunt-babel` and `@babel/preset-typescript`, though even that grunt plugin hasn't been updated in 5 years. 

It sucks that maintenance of non-SPA build tools seems to have fallen off a cliff. Sometimes I just need an old-school server-side site, y'know?
