### ISSUE TITLE
Compiling is slow

### ISSUE THREAD

**Issue by ljl** [TypeStrong/grunt-ts#7]
Using grunt-ts, compiling takes almost twice as long as the tsc compiler.

``` bash
$ time tsc main.ts -out test.js 
real    0m6.366s

$ grunt cm
Running "ts:api" (ts) task
Compiling.
Success: 14.38s for 1 typescript files
```

**Comment by danger89** [comment]
I don't have alot of issues, yet I don't like to wait for nothing. Could you please go a bit more into the details on this?

Like are there some best practices / examples (using grunt-ts with grunt parallel or grunt concurrent (or which one is now the best to use?)?

Also does somebody have some special flag and tricks in your tsconfig.json to speed things up?

Thanks!
