### ISSUE TITLE
Only compile changed files when using grunt-contrib-watch 

### ISSUE THREAD

**Issue by basarat** [TypeStrong/grunt-ts#70]
From https://github.com/jeffmay/angular-ts-seed/issues/1#issuecomment-36625847 

```
//Only recompile the ts files that have actually changed.
    var onChange = grunt.util._.debounce(function () {
        grunt.config('typescript.base.src', Object.keys(changedFiles));
        changedFiles = Object.create(null);
    }, 200);
    grunt.event.on('watch', function (action, filepath) {
        changedFiles[filepath] = action;
        onChange();
    });
```

Instead of expanding all the source.

**Comment by s093294** [comment]
I think myissue here , http://stackoverflow.com/questions/33080502/grunt-ts-watch-not-working-when-file-changed, is related to this.  The problem for me with the build in watch could be that my needed type definitions, "typings/vendors.d.ts","typings/tsd.d.ts", "!libs/**/*.ts" in .src is not included when it compiles the changed filse (from reading this issue i concluded that the src of the task is updated to only changed files)

**Comment by s093294** [comment]
my problem (using external watch) was that i missed: 
 ```
options: {
                    spawn: false,
                },
```
